# -*- coding: utf-8 -*-
"""CUBI Pipeline targeted_seq_cnv_export step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.targeted_seq_cnv_export import TargetedSeqCnvExportWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = TargetedSeqCnvExportWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())

# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    targeted_seq_cnv_export_link_out_run,
    # Writing pedigrees should be done locally as well
    targeted_seq_cnv_export_write_pedigree_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule targeted_seq_cnv_export_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# Variant Annotation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Write out pedigree file -----------------------------------------------------


rule targeted_seq_cnv_export_write_pedigree_run:
    input:
        unpack(wf.get_input_files("write_pedigree", "run")),
    output:
        wf.get_output_files("write_pedigree", "run"),
    run:
        wf.substep_dispatch("write_pedigree", "run", wildcards, output)


# Run varfish-annotator-cli annotate ------------------------------------------


rule targeted_seq_cnv_export_varfish_annotator_annotate_svs:
    input:
        **wf. get_input_files('varfish_annotator','annotate'),
    output:
        **wf. get_output_files('varfish_annotator','annotate'),
    threads: wf.get_resource("varfish_annotator", "annotate", "threads")
    resources:
        time=wf.get_resource("varfish_annotator", "annotate", "time"),
        memory=wf.get_resource("varfish_annotator", "annotate", "memory"),
        partition=wf.get_resource("varfish_annotator", "annotate", "partition"),
    log:
        **wf. get_log_file('varfish_annotator','annotate'),
    params:
        **{"args": wf. get_params('varfish_annotator','annotate')},
    wrapper:
        wf.wrapper_path("varfish_annotator/annotate_sv")
