# -*- coding: utf-8 -*-
"""CUBI Pipeline germline variant_checking step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.variant_checking import VariantCheckingWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = VariantCheckingWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    variant_checking_link_out_run,
    # Writing the pedigrees should be done locally
    variant_checking_write_pedigree_run,


rule variant_checking_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule variant_checking_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Variant Checking ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Write out pedigree file -----------------------------------------------------


rule variant_checking_write_pedigree_run:
    output:
        wf.get_output_files("write_pedigree", "run"),
    run:
        wf.substep_dispatch("write_pedigree", "run", wildcards, output)


# Run peddy -------------------------------------------------------------------


rule variant_checking_peddy_run:
    input:
        **wf.get_input_files("peddy", "run"),
    output:
        **wf.get_output_files("peddy", "run"),
    log:
        wf.get_log_file("peddy", "run"),
    threads: wf.get_resource("peddy", "run", "threads")
    resources:
        runtime=wf.get_resource("peddy", "run", "runtime"),
        mem=wf.get_resource("peddy", "run", "mem"),
        partition=wf.get_resource("peddy", "run", "partition"),
        tmpdir=wf.get_resource("peddy", "run", "tmpdir"),
    wrapper:
        wf.wrapper_path("peddy/run")
