# -*- coding: utf-8 -*-
"""CUBI Pipeline germline variant_checking step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.variant_checking import VariantCheckingWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = VariantCheckingWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())

# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    variant_checking_link_out_run,
    # Writing the pedigrees should be done locally
    variant_checking_write_pedigree_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule variant_checking_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# Variant Checking ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Write out pedigree file -----------------------------------------------------


rule variant_checking_write_pedigree_run:
    output:
        wf.get_output_files("write_pedigree", "run"),
    run:
        wf.substep_dispatch("write_pedigree", "run", wildcards, output)


# Run peddy -------------------------------------------------------------------


rule variant_checking_peddy_run:
    input:
        **wf. get_input_files('peddy','run'),
    output:
        **wf. get_output_files('peddy','run'),
    threads: wf.get_resource("peddy", "run", "threads")
    resources:
        time=wf.get_resource("peddy", "run", "time"),
        memory=wf.get_resource("peddy", "run", "memory"),
        partition=wf.get_resource("peddy", "run", "partition"),
    log:
        wf.get_log_file("peddy", "run"),
    wrapper:
        wf.wrapper_path("peddy/run")
