name: 'Install/Cache conda'
description: 'Install or retrieve a conda environment from cache'
inputs:
  python-version:
    required: true
    type: string
  environment-file:
    required: true
    type: string
  cache-number:
    required: false
    type: number
    default: 1

defaults:
  run:
    shell: bash -el {0}

runs:
  using: "composite"
  steps:
    - name: Cache conda packages
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ inputs.cache-number }}-${{ hashFiles(inputs.environment-file) }}
      id: cache

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ci_test_conda
        python-version: ${{ inputs.python-version }}
        pkgs-dirs: ~/conda_pkgs_dir
        environment-file: ${{ inputs.environment-file }}
        auto-update-conda: true
        use-mamba: true
