from ..workflows import (
    adapter_trimming,
    cbioportal_export,
    combine_variants,
    create_proteome,
    gene_expression_quantification,
    gene_expression_report,
    helper_gcnv_model_targeted,
    helper_gcnv_model_wgs,
    hla_typing,
    homologous_recombination_deficiency,
    igv_session_generation,
    ngs_data_qc,
    ngs_mapping,
    panel_of_normals,
    repeat_expansion,
    somatic_cnv_checking,
    somatic_gene_fusion_calling,
    somatic_hla_loh_calling,
    somatic_msi_calling,
    somatic_neoepitope_prediction,
    somatic_purity_ploidy_estimate,
    somatic_targeted_seq_cnv_calling,
    somatic_variant_signatures,
    somatic_wgs_cnv_calling,
    sv_calling_targeted,
    sv_calling_wgs,
    tumor_mutational_burden,
    varfish_export,
    variant_annotation,
    variant_calling,
    variant_checking,
    variant_export_external,
    variant_filtration,
    variant_phasing,
    wgs_cnv_export_external,
    wgs_sv_export_external,
)

STEP_TO_MODULE = {
    "adapter_trimming": adapter_trimming,
    "cbioportal_export": cbioportal_export,
    "combine_variants": combine_variants,
    "create_proteome": create_proteome,
    "gene_expression_quantification": gene_expression_quantification,
    "gene_expression_report": gene_expression_report,
    "helper_gcnv_model_targeted": helper_gcnv_model_targeted,
    "helper_gcnv_model_wgs": helper_gcnv_model_wgs,
    "hla_typing": hla_typing,
    "homologous_recombination_deficiency": homologous_recombination_deficiency,
    "igv_session_generation": igv_session_generation,
    "ngs_mapping": ngs_mapping,
    "ngs_data_qc": ngs_data_qc,
    "panel_of_normals": panel_of_normals,
    "repeat_analysis": repeat_expansion,
    "somatic_cnv_checking": somatic_cnv_checking,
    "somatic_gene_fusion_calling": somatic_gene_fusion_calling,
    "somatic_hla_loh_calling": somatic_hla_loh_calling,
    "somatic_msi_calling": somatic_msi_calling,
    "somatic_neoepitope_prediction": somatic_neoepitope_prediction,
    "somatic_purity_ploidy_estimate": somatic_purity_ploidy_estimate,
    "somatic_targeted_seq_cnv_calling": somatic_targeted_seq_cnv_calling,
    "somatic_variant_signatures": somatic_variant_signatures,
    "somatic_wgs_cnv_calling": somatic_wgs_cnv_calling,
    "sv_calling_targeted": sv_calling_targeted,
    "sv_calling_wgs": sv_calling_wgs,
    "tumor_mutational_burden": tumor_mutational_burden,
    "varfish_export": varfish_export,
    "variant_annotation": variant_annotation,
    "variant_calling": variant_calling,
    "variant_checking": variant_checking,
    "variant_export_external": variant_export_external,
    "variant_filtration": variant_filtration,
    "variant_phasing": variant_phasing,
    "wgs_cnv_export_external": wgs_cnv_export_external,
    "wgs_sv_export_external": wgs_sv_export_external,
}
