# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_msi_calling step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Clemens Messerschmidt"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_msi_calling_link_out_run,


rule somatic_msi_calling_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_msi_calling_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Somatic Microsatellite Instability analysis~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run MANTIS_msi2 ------------------------------------------------------------------


rule somatic_msi_calling_mantis_msi2:
    input:
        unpack(wf.get_input_files("mantis_msi2", "run")),
    output:
        **wf.get_output_files("mantis_msi2", "run"),
    log:
        **wf.get_log_file("mantis_msi2", "run"),
    threads: wf.get_resource("mantis_msi2", "run", "threads")
    resources:
        runtime=wf.get_resource("mantis_msi2", "run", "runtime"),
        mem=wf.get_resource("mantis_msi2", "run", "mem"),
        partition=wf.get_resource("mantis_msi2", "run", "partition"),
        tmpdir=wf.get_resource("mantis_msi2", "run", "tmpdir"),
    wrapper:
        wf.wrapper_path("mantis/mantis_msi2/run")
