# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_msi_calling step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.somatic_msi_calling import SomaticMsiCallingWorkflow

__author__ = "Clemens Messerschmidt"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = SomaticMsiCallingWorkflow(
    workflow, config, lookup_paths, config_paths, os.getcwd()
)

# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_msi_calling_link_out_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_msi_calling_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# Somatic Microsatellite Instability analysis~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run MANTIS_msi2 ------------------------------------------------------------------


rule somatic_msi_calling_mantis_msi2:
    input:
        unpack(wf.get_input_files("mantis_msi2", "run")),
    output:
        **wf.get_output_files("mantis_msi2", "run"),
    threads: wf.get_resource("mantis_msi2", "run", "threads")
    resources:
        time=wf.get_resource("mantis_msi2", "run", "time"),
        memory=wf.get_resource("mantis_msi2", "run", "memory"),
        partition=wf.get_resource("mantis_msi2", "run", "partition"),
        tmpdir=wf.get_resource("mantis_msi2", "run", "tmpdir"),
    log:
        **wf.get_log_file("mantis_msi2", "run"),
    wrapper:
        wf.wrapper_path("mantis/mantis_msi2/run")
