# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_variant_calling step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.panel_of_normals import PanelOfNormalsWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = PanelOfNormalsWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())
tool = str(wf.config.tool)


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    panel_of_normals_link_out_run,


rule panel_of_normals_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule panel_of_normals_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Panel of normals (Mutect2) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Select normals --------------------------------------------------------------

# rule panel_of_normals_mutect2_select_panel:
#     input: unpack(wf.get_input_files('mutect2', 'select_panel'))
#     output: **wf.get_output_files('mutect2', 'select_panel')
#     # log: **wf.get_log_file('mutect2', 'select_panel')
#     wrapper: wf.wrapper_path('mutect2/select_panel')

# Write out the tumor-only results for the normals ----------------------------

if tool == "mutect2":

    scattergather:
        mutect2=(
            getattr(wf.config, "mutect2", None).num_jobs
            if getattr(wf.config, "mutect2", None)
            else 24
        ),

    rule panel_of_normals_mutect2_scatter:
        input:
            unpack(wf.get_input_files("mutect2", "scatter")),
        output:
            **wf.get_output_files("mutect2", "scatter"),
        log:
            **wf.get_log_file("mutect2", "scatter"),
        localrule: True
        threads: 1
        resources:
            runtime=wf.get_resource("mutect2", "scatter", "runtime"),
            mem=wf.get_resource("mutect2", "scatter", "mem"),
            partition=wf.get_resource("mutect2", "scatter", "partition"),
            tmpdir=wf.get_resource("mutect2", "scatter", "tmpdir"),
        params:
            args=wf.get_args("mutect2", "scatter"),
        wrapper:
            wf.wrapper_path("split_regions")

    rule panel_of_normals_mutect2_prepare_panel:
        input:
            unpack(wf.get_input_files("mutect2", "prepare_panel")),
        output:
            **wf.get_output_files("mutect2", "prepare_panel"),
        log:
            **wf.get_log_file("mutect2", "prepare_panel"),
        threads: wf.get_resource("mutect2", "prepare_panel", "threads")
        resources:
            runtime=wf.get_resource("mutect2", "prepare_panel", "runtime"),
            mem=wf.get_resource("mutect2", "prepare_panel", "mem"),
            partition=wf.get_resource("mutect2", "prepare_panel", "partition"),
            tmpdir=wf.get_resource("mutect2", "prepare_panel", "tmpdir"),
        params:
            args=wf.get_args("mutect2", "prepare_panel"),
        wrapper:
            wf.wrapper_path("mutect2/run")

    rule panel_of_normals_mutect2_gather:
        input:
            unpack(wf.get_input_files("mutect2", "gather")),
        output:
            **wf.get_output_files("mutect2", "gather"),
        log:
            **wf.get_log_file("mutect2", "gather"),
        threads: 1
        resources:
            runtime=wf.get_resource("mutect2", "gather", "runtime"),
            mem=wf.get_resource("mutect2", "gather", "mem"),
            partition=wf.get_resource("mutect2", "gather", "partition"),
            tmpdir=wf.get_resource("mutect2", "gather", "tmpdir"),
        wrapper:
            wf.wrapper_path("mutect2/gather")

    rule panel_of_normals_mutect2_create_panel:
        input:
            unpack(wf.get_input_files("mutect2", "create_panel")),
        output:
            **wf.get_output_files("mutect2", "create_panel"),
        log:
            **wf.get_log_file("mutect2", "create_panel"),
        threads: wf.get_resource("mutect2", "create_panel", "threads")
        resources:
            runtime=wf.get_resource("mutect2", "create_panel", "runtime"),
            mem=wf.get_resource("mutect2", "create_panel", "mem"),
            partition=wf.get_resource("mutect2", "create_panel", "partition"),
            tmpdir=wf.get_resource("mutect2", "create_panel", "tmpdir"),
        params:
            args=wf.get_args("mutect2", "create_panel"),
        wrapper:
            wf.wrapper_path("mutect2/create_panel")


# Panel of normals (cnvkit) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

elif tool in ("cnvkit", "access"):

    rule panel_of_normals_access_run:
        output:
            **wf.get_output_files("access", "run"),
        log:
            **wf.get_log_file("access", "run"),
        resources:
            runtime=wf.get_resource("access", "run", "runtime"),
            mem=wf.get_resource("access", "run", "mem"),
            partition=wf.get_resource("access", "run", "partition"),
        wrapper:
            wf.wrapper_path("cnvkit/access")

    if tool == "cnvkit":

        rule panel_of_normals_cnvkit_target:
            input:
                unpack(wf.get_input_files("cnvkit", "target")),
            output:
                **wf.get_output_files("cnvkit", "target"),
            log:
                **wf.get_log_file("cnvkit", "target"),
            threads: wf.get_resource("cnvkit", "target", "threads")
            resources:
                runtime=wf.get_resource("cnvkit", "target", "runtime"),
                mem=wf.get_resource("cnvkit", "target", "mem"),
                partition=wf.get_resource("cnvkit", "target", "partition"),
            params:
                args=wf.get_args("cnvkit", "target"),
            wrapper:
                wf.wrapper_path("cnvkit/target")

        rule panel_of_normals_cnvkit_antitarget:
            input:
                unpack(wf.get_input_files("cnvkit", "antitarget")),
            output:
                **wf.get_output_files("cnvkit", "antitarget"),
            log:
                **wf.get_log_file("cnvkit", "antitarget"),
            threads: wf.get_resource("cnvkit", "antitarget", "threads")
            resources:
                runtime=wf.get_resource("cnvkit", "antitarget", "runtime"),
                mem=wf.get_resource("cnvkit", "antitarget", "mem"),
                partition=wf.get_resource("cnvkit", "antitarget", "partition"),
            params:
                args=wf.get_args("cnvkit", "antitarget"),
            wrapper:
                wf.wrapper_path("cnvkit/antitarget")

        rule panel_of_normals_cnvkit_coverage:
            input:
                unpack(wf.get_input_files("cnvkit", "coverage")),
            output:
                **wf.get_output_files("cnvkit", "coverage"),
            log:
                **wf.get_log_file("cnvkit", "coverage"),
            threads: wf.get_resource("cnvkit", "coverage", "threads")
            resources:
                runtime=wf.get_resource("cnvkit", "coverage", "runtime"),
                mem=wf.get_resource("cnvkit", "coverage", "mem"),
                partition=wf.get_resource("cnvkit", "coverage", "partition"),
            params:
                args=wf.get_args("cnvkit", "coverage"),
            wrapper:
                wf.wrapper_path("cnvkit/coverage")

        rule panel_of_normals_cnvkit_create_panel:
            input:
                unpack(wf.get_input_files("cnvkit", "create_panel")),
            output:
                **wf.get_output_files("cnvkit", "create_panel"),
            log:
                **wf.get_log_file("cnvkit", "create_panel"),
            threads: wf.get_resource("cnvkit", "create_panel", "threads")
            resources:
                runtime=wf.get_resource("cnvkit", "create_panel", "runtime"),
                mem=wf.get_resource("cnvkit", "create_panel", "mem"),
                partition=wf.get_resource("cnvkit", "create_panel", "partition"),
            params:
                args=wf.get_args("cnvkit", "create_panel"),
            wrapper:
                wf.wrapper_path("cnvkit/reference")

        rule panel_of_normals_cnvkit_report:
            input:
                unpack(wf.get_input_files("cnvkit", "report")),
            output:
                **wf.get_output_files("cnvkit", "report"),
            log:
                **wf.get_log_file("cnvkit", "report"),
            threads: wf.get_resource("cnvkit", "report", "threads")
            resources:
                runtime=wf.get_resource("cnvkit", "report", "runtime"),
                mem=wf.get_resource("cnvkit", "report", "mem"),
                partition=wf.get_resource("cnvkit", "report", "partition"),
            params:
                args=wf.get_args("cnvkit", "report"),
            wrapper:
                wf.wrapper_path("cnvkit/report")


# Panel of normals (PureCN) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

elif tool == "purecn":

    # Install the annotation R package --------------------------

    rule panel_of_normals_purecn_install:
        output:
            **wf.get_output_files("purecn", "install"),
        log:
            **wf.get_log_file("purecn", "install"),
        resources:
            runtime=wf.get_resource("purecn", "install", "runtime"),
            mem=wf.get_resource("purecn", "install", "mem"),
            partition=wf.get_resource("purecn", "install", "partition"),
        params:
            container="docker://markusriester/purecn",
        wrapper:
            wf.wrapper_path("singularity")

    rule panel_of_normals_purecn_prepare:
        input:
            **wf.get_input_files("purecn", "prepare"),
        output:
            **wf.get_output_files("purecn", "prepare"),
        log:
            **wf.get_log_file("purecn", "prepare"),
        resources:
            runtime=wf.get_resource("purecn", "prepare", "runtime"),
            mem=wf.get_resource("purecn", "prepare", "mem"),
            partition=wf.get_resource("purecn", "prepare", "partition"),
        wrapper:
            wf.wrapper_path("purecn/prepare")

    rule panel_of_normals_purecn_coverage:
        input:
            unpack(wf.get_input_files("purecn", "coverage")),
        output:
            **wf.get_output_files("purecn", "coverage"),
        log:
            **wf.get_log_file("purecn", "coverage"),
        resources:
            runtime=wf.get_resource("purecn", "coverage", "runtime"),
            mem=wf.get_resource("purecn", "coverage", "mem"),
            partition=wf.get_resource("purecn", "coverage", "partition"),
        params:
            args=wf.get_args("purecn", "coverage"),
        wrapper:
            wf.wrapper_path("purecn/coverage")

    rule panel_of_normals_purecn_create_panel:
        input:
            unpack(wf.get_input_files("purecn", "create_panel")),
        output:
            **wf.get_output_files("purecn", "create_panel"),
        log:
            **wf.get_log_file("purecn", "create_panel"),
        resources:
            runtime=wf.get_resource("purecn", "create_panel", "runtime"),
            mem=wf.get_resource("purecn", "create_panel", "mem"),
            partition=wf.get_resource("purecn", "create_panel", "partition"),
        wrapper:
            wf.wrapper_path("purecn/create_panel")
