line-length = 100

[lint]
select = ["E", "F", "I"] # "B": flake8-bugbear, "COM": trailing commas,
ignore = ["D", "F821", "E501"]  # E501: line too long, F821: name used but unknown (e.g. "snakemake" in wrapper files)
exclude = ["docs/conf.py"]
