# -*- coding: utf-8 -*-
"""CUBI Pipeline guess_sex step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.guess_sex import GuessSexWorkflow

__author__ = "Eric Blanc <eric.blanc@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = GuessSexWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())

# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    guess_sex_link_out_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule guess_sex_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# Actual actions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Samtools --------------------------------------------------------------------


rule guess_sex_samtools_run:
    input:
        unpack(wf.get_input_files("samtools", "run")),
    output:
        **wf.get_output_files("samtools", "run"),
    params:
        **{"args": wf.get_args("samtools", "run")},
    threads: wf.get_resource("samtools", "run", "threads")
    resources:
        time=wf.get_resource("samtools", "run", "time"),
        memory=wf.get_resource("samtools", "run", "memory"),
        partition=wf.get_resource("samtools", "run", "partition"),
        tmpdir=wf.get_resource("samtools", "run", "tmpdir"),
    log:
        **wf.get_log_file("samtools", "run"),
    wrapper:
        wf.wrapper_path("samtools/guess_sex")
