channels:
  - conda-forge
  - bioconda
  - http://conda.cubi.bihealth.org/cubiconda
  - nodefaults
dependencies:
  - gatk_nonfree==3.7
  - bcftools==1.12
  - samtools==1.12
  - htslib==1.12
  - coincbc==2.10.10
  - snakemake-minimal =8.25
