static_data_config:
  reference:
    path: ../../resources/refs/subregion.fa
  dbsnp:
    path: ../../resources/refs/dbsnp.vcf.gz

tasks:
  - name: mapping
    step: ngs_mapping
    config:
      tool: bwa
      bwa:
        path_index: ../../resources/refs/subregion
        mask_duplicates: false
        memory_bam_sort: 2G
        num_threads_bam_sort: 2
        num_threads_bam_view: 2
        num_threads_align: 2
      ngs_chew_fingerprint:
        enabled: false
      target_coverage_report:
        path_target_interval_list_mapping:
          - name: MedExome_hg19_empirical_targets
            pattern: MedExome
            path: resources/Exome-MedExome.chr12.bed

  - name: variant_calling
    step: variant_calling
    config:
      depends_on:
        ngs_mapping: mapping
      group_by: cohort
      tool: gatk4_hc_gvcf
      gatk4_hc_gvcf: {}

  - name: annotation
    step: variant_annotation
    config:
      depends_on:
        variant: variant_calling
      tool: "mehari"
      mehari:
        transcripts:
          - ../../resources/mehari/GRCh37-ensembl.chr12.txs.bin.zst
        assembly: GRCh37
        reference: ../../resources/refs/subregion.fa

  - name: filtration_final
    step: variant_filtration
    config:
      tool: vembrane
      depends_on:
        variant: annotation
      vembrane:
        mode: filter
        expression: 'QUAL > 10'
        extra_args: "--backend pysam"

data_sets:
  trbc:
    file: samplesheet.tsv
    search_patterns:
      - { left: '*.R1.fastq.gz', right: '*.R2.fastq.gz' }
    search_paths:
      - raw
    type: germline_variants
    naming_scheme: only_secondary_id
