# -*- coding: utf-8 -*-
"""CUBI Pipeline igv_session_generation step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking out the alignments should be done locally by the Snakemake
    # master process
    igv_session_generation_link_out_run,


rule igv_session_generation_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule igv_session_generation_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# IGV Session Generation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule igv_session_generation_write_igv_session_file:
    input:
        unpack(wf.get_input_files("write_igv_session_file", "run")),
    output:
        **wf.get_output_files("write_igv_session_file", "run"),
    threads: wf.get_resource("write_igv_session_file", "run", "threads")
    resources:
        runtime=wf.get_resource("write_igv_session_file", "run", "runtime"),
        mem=wf.get_resource("write_igv_session_file", "run", "mem"),
        partition=wf.get_resource("write_igv_session_file", "run", "partition"),
        tmpdir=wf.get_resource("write_igv_session_file", "run", "tmpdir"),
    run:
        wf.substep_dispatch("write_igv_session_file", "run", wildcards, output)
