# -*- coding: utf-8 -*-
"""CUBI Pipeline igv_session_generation step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.igv_session_generation import (
    IgvSessionGenerationWorkflow,
)

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = IgvSessionGenerationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


# Modules =====================================================================


target_upstream = wf.depends_on.get("ngs_mapping", "ngs_mapping")
upstream_prefix = wf.config.get(f"path_ngs_mapping", f"../{target_upstream}")


module ngs_mapping:
    snakefile:
        "../ngs_mapping/Snakefile"
    config:
        wf.w_config
    prefix:
        upstream_prefix


use rule * from ngs_mapping as ngs_mapping_*


if wf.config["path_variant_phasing"]:

    target_upstream = wf.depends_on.get("variant_phasing", "variant_phasing")
upstream_prefix = wf.config.get(f"path_variant_phasing", f"../{target_upstream}")


module variant_phasing:
    snakefile:
        "../variant_phasing/Snakefile"
    config:
        wf.w_config
    prefix:
        upstream_prefix


use rule * from variant_phasing as variant_phasing_*


if wf.config["path_variant_annotation"]:

    target_upstream = wf.depends_on.get("variant_annotation", "variant_annotation")
upstream_prefix = wf.config.get(f"path_variant_annotation", f"../{target_upstream}")


module variant_annotation:
    snakefile:
        "../variant_annotation/Snakefile"
    config:
        wf.w_config
    prefix:
        upstream_prefix


use rule * from variant_annotation as variant_annotation_*


if wf.config["path_variant_calling"]:

    target_upstream = wf.depends_on.get("variant_calling", "variant_calling")
upstream_prefix = wf.config.get(f"path_variant_calling", f"../{target_upstream}")


module variant_calling:
    snakefile:
        "../variant_calling/Snakefile"
    config:
        wf.w_config
    prefix:
        upstream_prefix


use rule * from variant_calling as variant_calling_*


# Rules =======================================================================


localrules:
    # Linking out the alignments should be done locally by the Snakemake
    # master process
    igv_session_generation_link_out_run,


rule igv_session_generation_all:
    input:
        wf.get_result_files(),
    default_target: True


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule igv_session_generation_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# IGV Session Generation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule igv_session_generation_write_igv_session_file:
    input:
        unpack(wf.get_input_files("write_igv_session_file", "run")),
    output:
        **wf.get_output_files("write_igv_session_file", "run"),
    threads: wf.get_resource("write_igv_session_file", "run", "threads")
    resources:
        runtime=wf.get_resource("write_igv_session_file", "run", "runtime"),
        mem=wf.get_resource("write_igv_session_file", "run", "mem"),
        partition=wf.get_resource("write_igv_session_file", "run", "partition"),
        tmpdir=wf.get_resource("write_igv_session_file", "run", "tmpdir"),
    run:
        wf.substep_dispatch("write_igv_session_file", "run", wildcards, output)
