# -*- coding: utf-8 -*-
"""CUBI Pipeline igv_session_generation step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.igv_session_generation import IgvSessionGenerationWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = IgvSessionGenerationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())

# Rules =======================================================================


localrules:
    # Linking out the alignments should be done locally by the Snakemake
    # master process
    igv_session_generation_link_out_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule igv_session_generation_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# IGV Session Generation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule igv_session_generation_write_igv_session_file:
    input:
        unpack(wf.get_input_files("write_igv_session_file", "run")),
    output:
        **wf. get_output_files('write_igv_session_file','run'),
    threads: wf.get_resource("write_igv_session_file", "run", "threads")
    resources:
        time=wf.get_resource("write_igv_session_file", "run", "time"),
        mem=wf.get_resource("write_igv_session_file", "run", "memory"),
        partition=wf.get_resource("write_igv_session_file", "run", "partition"),
    run:
        wf.substep_dispatch("write_igv_session_file", "run", wildcards, output)
