# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_wgs_sv_calling step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.somatic_wgs_sv_calling import SomaticWgsSvCallingWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = SomaticWgsSvCallingWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


# Modules =====================================================================


target_upstream = wf.depends_on.get("ngs_mapping", "ngs_mapping")
upstream_prefix = wf.config.get(f"path_ngs_mapping", f"../{target_upstream}")


module ngs_mapping:
    snakefile:
        "../ngs_mapping/Snakefile"
    config:
        wf.w_config
    prefix:
        upstream_prefix


use rule * from ngs_mapping as ngs_mapping_*


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_wgs_sv_calling_link_out_run,


rule somatic_wgs_sv_calling_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_wgs_sv_calling_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Somatic Variant Calling ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run Manta -------------------------------------------------------------------


rule somatic_wgs_sv_calling_manta_run:
    input:
        unpack(wf.get_input_files("manta", "run")),
    output:
        **wf.get_output_files("manta", "run"),
    log:
        wf.get_log_file("manta", "run"),
    threads: wf.get_resource("manta", "run", "threads")
    resources:
        runtime=wf.get_resource("manta", "run", "runtime"),
        mem=wf.get_resource("manta", "run", "mem"),
        partition=wf.get_resource("manta", "run", "partition"),
        tmpdir=wf.get_resource("manta", "run", "tmpdir"),
    wrapper:
        wf.wrapper_path("manta/somatic_wgs")
