# -*- coding: utf-8 -*-
"""CUBI Pipeline germline_variant_annotation step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.germline_variant_annotation import (
    GermlineVariantAnnotationWorkflow,
)

__author__ = "Eric Blanc <eric.blanc@bih-charite.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = GermlineVariantAnnotationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())
tools = wf.config["tools"]


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    any_variant_annotation_link_out_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule any_variant_annotation_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


include: "../any_variant_annotation/Snakefile"
