channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bcftools==1.19
  - htslib==1.19.1
  - samtools==1.19.2
  - varfish-annotator-cli==0.32
  - openjdk==8.0.382
  - jq==1.7.1
  - vcfpy==0.13.8
  - pysam==0.22.0
