channels:
- conda-forge
- bioconda

dependencies:
- python =3.9
- gatk4 =4.3
- htslib >=1.9
- bcftools >=1.9
- datrie
- gawk =5.1
# snakemake needed by the parallel wrapper
- snakemake-minimal =7
# needed by snakemake
- cffi
- numpy
- pandas
