channels:
  - conda-forge
  - bioconda
  - http://conda.cubi.bihealth.org/cubiconda
dependencies:
  - ebfilter==0.2.2
  - vcfpy==0.13.8
  - pysam==0.22.0
  - scipy==1.12.0
  - numpy==1.26.4
  - bcftools==1.19
  - htslib==1.19.1
  - samtools==1.19.2
  - snakemake-minimal==7.32.4
  - cffi==1.16.0
  - pandas==2.2.1
