# -*- coding: utf-8 -*-
"""CUBI Pipeline variant_combination step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.variant_combination import VariantCombinationWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = VariantCombinationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())

# Rules =======================================================================


localrules:
    # Writing the PED files should be done locally
    variant_combination_write_pedigree_run,
    # Linking files from work/ to output/ should be done locally
    variant_combination_link_out_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule variant_combination_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# Variant Combination ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Write out pedigree file -----------------------------------------------------


rule variant_combination_write_pedigree_run:
    output:
        wf.get_output_files("write_pedigree", "run"),
    run:
        wf.substep_dispatch("write_pedigree", "run", wildcards, output)


# Variant Intersection --------------------------------------------------------


rule variant_combination_vars_intersect_run:
    input:
        unpack(wf.get_input_files("vars_intersect", "run")),
    output:
        **wf. get_output_files('vars_intersect','run'),
    threads: wf.get_resource("vars_intersect", "run", "threads")
    resources:
        time=wf.get_resource("vars_intersect", "run", "time"),
        memory=wf.get_resource("vars_intersect", "run", "memory"),
        partition=wf.get_resource("vars_intersect", "run", "partition"),
    params:
        args=wf.substep_dispatch("vars_intersect", "get_args", "run"),
    log:
        wf.get_log_file("vars_intersect", "run"),
    wrapper:
        wf.wrapper_path("variant_combination/vars_intersect")


# Variants Share Interval -----------------------------------------------------


rule variant_combination_vars_share_interval_run:
    input:
        unpack(wf.get_input_files("vars_share_interval", "run")),
    output:
        **wf. get_output_files('vars_share_interval','run'),
    threads: wf.get_resource("vars_share_interval", "run", "threads")
    resources:
        time=wf.get_resource("vars_share_interval", "run", "time"),
        memory=wf.get_resource("vars_share_interval", "run", "memory"),
        partition=wf.get_resource("vars_share_interval", "run", "partition"),
    params:
        args=wf.substep_dispatch("vars_share_interval", "get_args", "run"),
    log:
        wf.get_log_file("vars_share_interval", "run"),
    wrapper:
        wf.wrapper_path("variant_combination/vars_share_interval")
