# -*- coding: utf-8 -*-
"""CUBI Pipeline ngs_data_qc step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking the FASTQ files in and linking out the files should be done
    # locally by the Snakemake master process
    ngs_data_qc_link_out_run,


rule ngs_data_qc_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule ngs_data_qc_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Raw Data QC ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run FastQC ------------------------------------------------------------------


rule ngs_data_qc_fastqc_run:
    input:
        unpack(wf.get_input_files("fastqc", "run")),
    output:
        **wf.get_output_files("fastqc", "run"),
    log:
        **wf.get_log_file("fastqc", "run"),
    threads: wf.get_resource("fastqc", "run", "threads")
    resources:
        runtime=wf.get_resource("fastqc", "run", "runtime"),
        mem=wf.get_resource("fastqc", "run", "mem"),
        partition=wf.get_resource("fastqc", "run", "partition"),
        tmpdir=wf.get_resource("fastqc", "run", "tmpdir"),
    params:
        args=wf.get_params("fastqc", "run"),
    wrapper:
        wf.wrapper_path("fastqc")


# Bam Data QC ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run picard ------------------------------------------------------------------


rule ngs_data_qc_picard_prepare:
    input:
        unpack(wf.get_input_files("picard", "prepare")),
    output:
        **wf.get_output_files("picard", "prepare"),
    log:
        **wf.get_log_file("picard", "prepare"),
    threads: wf.get_resource("picard", "prepare", "threads")
    resources:
        runtime=wf.get_resource("picard", "prepare", "runtime"),
        mem=wf.get_resource("picard", "prepare", "mem"),
        partition=wf.get_resource("picard", "prepare", "partition"),
        tmpdir=wf.get_resource("picard", "prepare", "tmpdir"),
    wrapper:
        wf.wrapper_path("picard/prepare")


rule ngs_data_qc_picard_metrics:
    input:
        unpack(wf.get_input_files("picard", "metrics")),
    output:
        **wf.get_output_files("picard", "metrics"),
    log:
        **wf.get_log_file("picard", "metrics"),
    threads: wf.get_resource("picard", "metrics", "threads")
    resources:
        runtime=wf.get_resource("picard", "metrics", "runtime"),
        mem=wf.get_resource("picard", "metrics", "mem"),
        partition=wf.get_resource("picard", "metrics", "partition"),
        tmpdir=wf.get_resource("picard", "metrics", "tmpdir"),
    params:
        args=wf.get_params("picard", "metrics"),
    wrapper:
        wf.wrapper_path("picard/metrics")
