# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_targeted_seq_cnv_calling step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.somatic_targeted_seq_cnv_calling import (
    SomaticTargetedSeqCnvCallingWorkflow,
)

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = SomaticTargetedSeqCnvCallingWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())
tool = str(wf.config.tool)


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_targeted_seq_cnv_calling_link_out_run,


rule somatic_targeted_seq_cnv_calling_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_targeted_seq_cnv_calling_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Somatic Targeted Sequencing CNV Calling ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# cnvkit pipeline -------------------------------------------------------------


# cnvkit requires a large number of rules, thus externalized
if tool == "cnvkit":

    include: "cnvkit.rules"


# Run sequenza ----------------------------------------------------


if tool == "sequenza":

    rule somatic_targeted_seq_cnv_calling_sequenza_install:
        output:
            **wf.get_output_files("sequenza", "install"),
        log:
            **wf.get_log_file("sequenza", "install"),
        threads: wf.get_resource("sequenza", "install", "threads")
        resources:
            runtime=wf.get_resource("sequenza", "install", "runtime"),
            mem=wf.get_resource("sequenza", "install", "mem"),
            partition=wf.get_resource("sequenza", "install", "partition"),
            tmpdir=wf.get_resource("sequenza", "install", "tmpdir"),
        params:
            packages=[
                {"name": "aroneklund/copynumber", "repo": "github"},
                {"name": "sequenzatools/sequenza@3.0.0", "repo": "bitbucket"},
            ],
        wrapper:
            wf.wrapper_path("sequenza/install")

    rule somatic_targeted_seq_cnv_calling_sequenza_gcreference:
        output:
            **wf.get_output_files("sequenza", "gcreference"),
        log:
            **wf.get_log_file("sequenza", "gcreference"),
        threads: wf.get_resource("sequenza", "gcreference", "threads")
        resources:
            runtime=wf.get_resource("sequenza", "gcreference", "runtime"),
            mem=wf.get_resource("sequenza", "gcreference", "mem"),
            partition=wf.get_resource("sequenza", "gcreference", "partition"),
            tmpdir=wf.get_resource("sequenza", "gcreference", "tmpdir"),
        params:
            args=wf.get_args("sequenza", "gcreference"),
        wrapper:
            wf.wrapper_path("sequenza/gcreference")

    rule somatic_targeted_seq_cnv_calling_sequenza_coverage:
        input:
            unpack(wf.get_input_files("sequenza", "coverage")),
        output:
            **wf.get_output_files("sequenza", "coverage"),
        log:
            **wf.get_log_file("sequenza", "coverage"),
        threads: wf.get_resource("sequenza", "coverage", "threads")
        resources:
            runtime=wf.get_resource("sequenza", "coverage", "runtime"),
            mem=wf.get_resource("sequenza", "coverage", "mem"),
            partition=wf.get_resource("sequenza", "coverage", "partition"),
            tmpdir=wf.get_resource("sequenza", "coverage", "tmpdir"),
        params:
            args=wf.get_args("sequenza", "coverage"),
        wrapper:
            wf.wrapper_path("sequenza/coverage")

    rule somatic_targeted_seq_cnv_calling_sequenza_run:
        input:
            unpack(wf.get_input_files("sequenza", "run")),
        output:
            **wf.get_output_files("sequenza", "run"),
        log:
            **wf.get_log_file("sequenza", "run"),
        threads: wf.get_resource("sequenza", "run", "threads")
        resources:
            runtime=wf.get_resource("sequenza", "run", "runtime"),
            mem=wf.get_resource("sequenza", "run", "mem"),
            partition=wf.get_resource("sequenza", "run", "partition"),
            tmpdir=wf.get_resource("sequenza", "run", "tmpdir"),
        params:
            args=wf.get_args("sequenza", "run"),
        wrapper:
            wf.wrapper_path("sequenza/run")


# Run PureCN ------------------------------------------------------


if tool == "purecn":

    rule somatic_targeted_seq_cnv_calling_purecn_coverage:
        input:
            unpack(wf.get_input_files("purecn", "coverage")),
        output:
            **wf.get_output_files("purecn", "coverage"),
        log:
            **wf.get_log_file("purecn", "coverage"),
        threads: wf.get_resource("purecn", "coverage", "threads")
        resources:
            runtime=wf.get_resource("purecn", "coverage", "runtime"),
            mem=wf.get_resource("purecn", "coverage", "mem"),
            partition=wf.get_resource("purecn", "coverage", "partition"),
            tmpdir=wf.get_resource("purecn", "coverage", "tmpdir"),
        params:
            args=wf.get_args("purecn", "coverage"),
        wrapper:
            wf.wrapper_path("purecn/coverage")

    rule somatic_targeted_seq_cnv_calling_purecn_run:
        input:
            unpack(wf.get_input_files("purecn", "run")),
        output:
            **wf.get_output_files("purecn", "run"),
        log:
            **wf.get_log_file("purecn", "run"),
        threads: wf.get_resource("purecn", "run", "threads")
        resources:
            runtime=wf.get_resource("purecn", "run", "runtime"),
            mem=wf.get_resource("purecn", "run", "mem"),
            partition=wf.get_resource("purecn", "run", "partition"),
            tmpdir=wf.get_resource("purecn", "run", "tmpdir"),
        params:
            args=wf.get_args("purecn", "run"),
        wrapper:
            wf.wrapper_path("purecn/run")
