channels:
  - conda-forge
  - bioconda
  - file:///data/gpfs-1/scratch/users/holtgrem_c/art/LinuxArtifacts/packages
dependencies:
  - gatk4 ==4.3.0.0
  - bcftools
  - htslib
  - parallel
  # the hard to install gcnvkernel
  - gcnvkernel ==0.8
  # gcnvkernel dependencies
  - conda-forge::python =3.6.10
  - pip =20.0.2
  - conda-forge::mkl =2019.5
  - conda-forge::mkl-service =2.3.0
  - conda-forge::numpy =1.17.5
  - conda-forge::theano =1.0.4
  - defaults::tensorflow =1.15.0
  - conda-forge::scipy =1.0.0
  - conda-forge::pymc3 =3.1
  - conda-forge::h5py =2.10.0 
  - conda-forge::keras =2.2.4
  - defaults::intel-openmp =2019.4
  - conda-forge::scikit-learn =0.23.1
  - conda-forge::matplotlib =3.2.1
  - conda-forge::pandas =1.0.3
  - conda-forge::typing_extensions =4.1.1
  - conda-forge::dill =0.3.4
  - r-base =3.6.2
  - r-data.table =1.12.8
  - r-dplyr =0.8.5
  - r-getopt =1.20.3
  - r-ggplot2 =3.3.0
  - r-gplots =3.0.3
  - r-gsalib =2.1
  - r-optparse =1.6.4
  - r-backports =1.1.10
  - biopython =1.76
  - pyvcf =0.6.8
  - bioconda::pysam =0.15.3

