channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base==4.3.3
  - r-dplyr==1.1.4
  - r-ggplot2==3.5.0
  - bioconductor-variantannotation==1.48.1
  - bioconductor-biostrings==2.70.1
