# -*- coding: utf-8 -*-
"""CUBI Pipeline variant_annotation step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.variant_annotation import VariantAnnotationWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = VariantAnnotationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())

# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    variant_annotation_link_out_run,
    # Writing pedigrees should be done locally as well
    variant_annotation_write_pedigree_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule variant_annotation_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# Variant Annotation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Write out pedigree file -----------------------------------------------------


rule variant_annotation_write_pedigree_run:
    output:
        wf.get_output_files("write_pedigree", "run"),
    run:
        wf.substep_dispatch("write_pedigree", "run", wildcards, output)


# Run Jannovar annotate-vcf ---------------------------------------------------


rule variant_annotation_jannovar_annotate_vcf:
    input:
        **wf. get_input_files('jannovar','annotate_vcf'),
    output:
        **wf. get_output_files('jannovar','annotate_vcf'),
    threads: wf.get_resource("jannovar", "annotate_vcf", "threads")
    resources:
        time=wf.get_resource("jannovar", "annotate_vcf", "time"),
        mem=wf.get_resource("jannovar", "annotate_vcf", "memory"),
        partition=wf.get_resource("jannovar", "annotate_vcf", "partition"),
    log:
        **wf. get_log_file('jannovar','annotate_vcf'),
    wrapper:
        wf.wrapper_path("jannovar_par/annotate_vcf")
