# -*- coding: utf-8 -*-
"""SNAPPY Pipeline variant_annotation step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.variant_annotation import VariantAnnotationWorkflow
from snappy_pipeline.workflows.variant_annotation.model import Tool

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = VariantAnnotationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally.
    variant_annotation_link_out_run,


rule variant_annotation_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule variant_annotation_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Variant Annotation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if wf.config.tool == Tool.vep:

    rule variant_annotation_vep:
        input:
            unpack(wf.get_input_files("vep", "run")),
        output:
            **wf.get_output_files("vep", "run"),
        log:
            **wf.get_log_file("vep", "run"),
        threads: wf.get_resource("vep", "run", "threads")
        resources:
            runtime=wf.get_resource("vep", "run", "runtime"),
            mem=wf.get_resource("vep", "run", "mem"),
            partition=wf.get_resource("vep", "run", "partition"),
            tmpdir=wf.get_resource("vep", "run", "tmpdir"),
        params:
            args=wf.get_args("vep", "run"),
        wrapper:
            wf.wrapper_path("vep/run")

elif wf.config.tool == Tool.mehari:

    rule variant_annotation_mehari:
        input:
            unpack(wf.get_input_files("mehari", "run")),
        output:
            **wf.get_output_files("mehari", "run"),
        log:
            **wf.get_log_file("mehari", "run"),
        threads: wf.get_resource("mehari", "run", "threads")
        resources:
            runtime=wf.get_resource("mehari", "run", "runtime"),
            mem=wf.get_resource("mehari", "run", "mem"),
            partition=wf.get_resource("mehari", "run", "partition"),
            tmpdir=wf.get_resource("mehari", "run", "tmpdir"),
        params:
            args=wf.get_args("mehari", "run"),
        wrapper:
            wf.wrapper_path("mehari/run")

else:
    raise ValueError(f"unknown tool {wf.config.tool}")
