# -*- coding: utf-8 -*-
"""CUBI Pipeline hla_typing step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.hla_typing import HlaTypingWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = HlaTypingWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())
tools = wf.w_config.step_config["hla_typing"].tools

# Rules =======================================================================


localrules:
    # Linking the FASTQ files in and linking out the alignments should
    # be done locally by the Snakemake master process
    hla_typing_link_in_run,
    hla_typing_link_out_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Link in FASTQ files ---------------------------------------------------------


rule hla_typing_link_in_run:
    input:
        wf.get_input_files("link_in", "run"),
    output:
        wf.get_output_files("link_in", "run"),
    run:
        shell(wf.get_shell_cmd("link_in", "run", wildcards))


# Generic linking out ---------------------------------------------------------


rule hla_typing_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


# HLA Typing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# OptiType --------------------------------------------------------------------


if "optitype" in tools["dna"] or "optitype" in tools["rna"]:

    rule hla_typing_optitype_run:
        input:
            **wf.get_input_files("optitype", "run"),
        output:
            **wf.get_output_files("optitype", "run"),
        threads: wf.get_resource("optitype", "run", "threads")
        resources:
            time=wf.get_resource("optitype", "run", "time"),
            memory=wf.get_resource("optitype", "run", "memory"),
            partition=wf.get_resource("optitype", "run", "partition"),
            tmpdir=wf.get_resource("optitype", "run", "tmpdir"),
        log:
            **wf.get_log_file("optitype", "run"),
        params:
            args=wf.get_args("optitype", "run"),
        wrapper:
            wf.wrapper_path("optitype")


# arcasHLA --------------------------------------------------------------------


# NB: reference is updated in the installed package
if "arcashla" in tools["rna"]:

    rule hla_typing_arcashla_prepare_reference:
        output:
            done="work/arcashla.prepare_reference/out/.done",
        params:
            reference_version="3.46.0",  # See https://github.com/RabadanLab/arcasHLA/pull/132
        log:
            "work/arcashla.prepare_reference/log/arcashla.prepare_reference.log",
        wrapper:
            wf.wrapper_path("arcashla/prepare_reference")

    rule hla_typing_arcashla_run:
        input:
            unpack(wf.get_input_files("arcashla", "run")),
        output:
            **wf.get_output_files("arcashla", "run"),
        params:
            args=wf.get_args("arcashla", "run"),
        threads: wf.get_resource("arcashla", "run", "threads")
        resources:
            time=wf.get_resource("arcashla", "run", "time"),
            memory=wf.get_resource("arcashla", "run", "memory"),
            partition=wf.get_resource("arcashla", "run", "partition"),
            tmpdir=wf.get_resource("arcashla", "run", "tmpdir"),
        log:
            **wf.get_log_file("arcashla", "run"),
        wrapper:
            wf.wrapper_path("arcashla/run")


# HLA*LA ----------------------------------------------------------------------


# NB: reference is updated in the installed package
if "hla_la" in tools["dna"] or "hla_la" in tools["rna"]:

    rule hla_typing_hla_la_prepare_graph:
        output:
            **wf.get_output_files("hla_la", "prepare_graph"),
        params:
            url="http://www.well.ox.ac.uk/downloads/PRG_MHC_GRCh38_withIMGT.tar.gz",
            expected_md5="525a8aa0c7f357bf29fe2c75ef1d477d",
        log:
            "work/hla_la.prepareGraph/log/hla_la.prepareGraph.log",
        resources:
            time=wf.get_resource("hla_la", "prepare_graph", "time"),
            memory=wf.get_resource("hla_la", "prepare_graph", "memory"),
            partition=wf.get_resource("hla_la", "prepare_graph", "partition"),
            tmpdir=wf.get_resource("hla_la", "prepare_graph", "tmpdir"),
        wrapper:
            wf.wrapper_path("hla_la/prepareGraph")

    rule hla_typing_hla_la_prepare_reference:
        input:
            unpack(wf.get_input_files("hla_la", "prepare_reference")),
        output:
            **wf.get_output_files("hla_la", "prepare_reference"),
        params:
            args=wf.get_args("hla_la", "prepare_reference"),
        log:
            "work/hla_la.prepare_reference/log/hla_la.prepare_reference.log",
        shell:
            r"""
                cut -f 1,2 {input.reference} \
                | awk -F '\t' '
                BEGIN {{printf "contigID\tcontigLength\tExtractCompleteContig\tPartialExtraction_Start\tPartialExtraction_Stop\n"}}
                {{
                    if ($0 ~ /^(chr)?6\t/) {{
                        printf "%s\t0\t{params.args[start]}\t{params.args[end]}\n", $0
                    }} else {{
                        printf "%s\t0\t\t\n", $0
                    }}
                }}
                END {{printf "*\t0\t1\t\t\n"}}' \
                > {output.reference}
            """

    rule hla_typing_hla_la_run:
        input:
            unpack(wf.get_input_files("hla_la", "run")),
        output:
            **wf.get_output_files("hla_la", "run"),
        params:
            args=wf.get_args("hla_la", "run"),
        threads: wf.get_resource("hla_la", "run", "threads")
        resources:
            time=wf.get_resource("hla_la", "run", "time"),
            memory=wf.get_resource("hla_la", "run", "memory"),
            partition=wf.get_resource("hla_la", "run", "partition"),
            tmpdir=wf.get_resource("hla_la", "run", "tmpdir"),
        log:
            **wf.get_log_file("hla_la", "run"),
        wrapper:
            wf.wrapper_path("hla_la/run")
