# -*- coding: utf-8 -*-
"""CUBI Pipeline hla_typing step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])

# Rules =======================================================================


localrules:
    # Linking the FASTQ files in and linking out the alignments should
    # be done locally by the Snakemake master process
    hla_typing_link_out_run,


rule hla_typing_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule hla_typing_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# HLA Typing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# OptiType --------------------------------------------------------------------


if wf.config.tool == "optitype":

    rule hla_typing_optitype_run:
        input:
            unpack(wf.get_input_files("optitype", "run")),
        output:
            **wf.get_output_files("optitype", "run"),
        log:
            **wf.get_log_file("optitype", "run"),
        threads: wf.get_resource("optitype", "run", "threads")
        resources:
            runtime=wf.get_resource("optitype", "run", "runtime"),
            mem=wf.get_resource("optitype", "run", "mem"),
            partition=wf.get_resource("optitype", "run", "partition"),
            tmpdir=wf.get_resource("optitype", "run", "tmpdir"),
        params:
            args=wf.get_params("optitype", "run"),
        wrapper:
            wf.wrapper_path("optitype")


# arcasHLA --------------------------------------------------------------------


if wf.config.tool == "arcashla":

    rule hla_typing_arcashla_prepare_reference:
        output:
            done="work/prepare_reference/out/.done",
        log:
            log="work/prepare_reference/log/prepare_reference.log",
            conda_list="work/prepare_reference/log/prepare_reference.conda_list.txt",
            conda_info="work/prepare_reference/log/prepare_reference.conda_info.txt",
        params:
            reference_version="3.24.0",  # See https://github.com/RabadanLab/arcasHLA/pull/132
        wrapper:
            wf.wrapper_path("arcashla/prepare_reference")

    rule hla_typing_arcashla_run:
        input:
            unpack(wf.get_input_files("arcashla", "run")),
        output:
            **wf.get_output_files("arcashla", "run"),
        log:
            **wf.get_log_file("arcashla", "run"),
        threads: wf.get_resource("arcashla", "run", "threads")
        resources:
            runtime=wf.get_resource("arcashla", "run", "runtime"),
            mem=wf.get_resource("arcashla", "run", "mem"),
            partition=wf.get_resource("arcashla", "run", "partition"),
            tmpdir=wf.get_resource("arcashla", "run", "tmpdir"),
        wrapper:
            wf.wrapper_path("arcashla/run")
