channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - minimap2 ==2.24
  - samtools ==1.9
  - htslib ==1.9
  # NB: gnuplot 5.2.7 is incompatible with samtools ==1.9
  # see https://github.com/samtools/samtools/issues/1065
  - gnuplot ==5.2.6
  - libpng ==1.6.37
  - inline-html ==1.0.0
