# -*- coding: utf-8 -*-
"""CUBI Pipeline variant_calling step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.variant_calling import VariantCallingWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = VariantCallingWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())

# Rules =======================================================================


localrules:
    # Writing pedigrees should be done locally as well
    variant_calling_write_pedigree_run,


rule all:
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Variant Calling ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Write out pedigree file -----------------------------------------------------


rule variant_calling_write_pedigree_run:
    input:
        unpack(wf.get_input_files("write_pedigree", "run")),
    output:
        wf.get_output_files("write_pedigree", "run"),
    run:
        wf.substep_dispatch("write_pedigree", "run", wildcards, output)


# Run bcftools call -----------------------------------------------------------


rule variant_calling_bcftools_call_run:
    input:
        unpack(wf.get_input_files("bcftools_call", "run")),
    output:
        **wf.get_output_files("bcftools_call", "run"),
    threads: wf.get_resource("bcftools_call", "run", "threads")
    resources:
        time=wf.get_resource("bcftools_call", "run", "time"),
        memory=wf.get_resource("bcftools_call", "run", "memory"),
        partition=wf.get_resource("bcftools_call", "run", "partition"),
        tmpdir=wf.get_resource("bcftools_call", "run", "tmpdir"),
    log:
        **wf.get_log_file("bcftools_call", "run"),
    wrapper:
        wf.wrapper_path("bcftools_call")


# Run Clair 3 -----------------------------------------------------------------


# Discover variants with Clair 3, create per-sample gVCF file
rule variant_calling_clair3_discover:
    input:
        unpack(wf.get_input_files("clair3", "discover")),
    output:
        **wf.get_output_files("clair3", "discover"),
    threads: wf.get_resource("clair3", "discover", "threads")
    resources:
        time=wf.get_resource("clair3", "discover", "time"),
        memory=wf.get_resource("clair3", "discover", "memory"),
        partition=wf.get_resource("clair3", "discover", "partition"),
        tmpdir=wf.get_resource("clair3", "discover", "tmpdir"),
    params:
        args=wf.substep_dispatch("clair3", "get_args", "discover"),
    log:
        **wf.get_log_file("clair3", "discover"),
    wrapper:
        wf.wrapper_path("clair3/discover")


# Combine the gVCF files from the pedigree with GLNexus 
rule variant_calling_clair3_genotype:
    input:
        unpack(wf.get_input_files("clair3", "genotype")),
    output:
        **wf.get_output_files("clair3", "genotype"),
    threads: wf.get_resource("clair3", "genotype", "threads")
    resources:
        time=wf.get_resource("clair3", "genotype", "time"),
        memory=wf.get_resource("clair3", "genotype", "memory"),
        partition=wf.get_resource("clair3", "genotype", "partition"),
        tmpdir=wf.get_resource("clair3", "genotype", "tmpdir"),
    params:
        step_key="variant_calling",
        caller_key="clair3",
    log:
        **wf.get_log_file("clair3", "genotype"),
    wrapper:
        wf.wrapper_path("clair3/genotype")


# Run GATK HaplotypeCaller (direct, pedigree/multi-sample) --------------------


rule variant_calling_gatk3_hc_run:
    input:
        unpack(wf.get_input_files("gatk3_hc", "run")),
    output:
        **wf.get_output_files("gatk3_hc", "run"),
    threads: wf.get_resource("gatk3_hc", "run", "threads")
    resources:
        time=wf.get_resource("gatk3_hc", "run", "time"),
        memory=wf.get_resource("gatk3_hc", "run", "memory"),
        partition=wf.get_resource("gatk3_hc", "run", "partition"),
        tmpdir=wf.get_resource("gatk3_hc", "run", "tmpdir"),
    log:
        **wf.get_log_file("gatk3_hc", "run"),
    wrapper:
        wf.wrapper_path("gatk3_hc")


# Run GATK UnifiedGenotyper ---------------------------------------------------


rule variant_calling_gatk3_ug_run:
    input:
        unpack(wf.get_input_files("gatk3_ug", "run")),
    output:
        **wf.get_output_files("gatk3_ug", "run"),
    threads: wf.get_resource("gatk3_ug", "run", "threads")
    resources:
        time=wf.get_resource("gatk3_ug", "run", "time"),
        memory=wf.get_resource("gatk3_ug", "run", "memory"),
        partition=wf.get_resource("gatk3_ug", "run", "partition"),
        tmpdir=wf.get_resource("gatk3_ug", "run", "tmpdir"),
    log:
        **wf.get_log_file("gatk3_ug", "run"),
    wrapper:
        wf.wrapper_path("gatk3_ug")


# Run GATK 4 HaplotypeCaller Joint (direct, pedigree/multi-sample) ------------


rule variant_calling_gatk4_hc_joint_run:
    input:
        unpack(wf.get_input_files("gatk4_hc_joint", "run")),
    output:
        **wf.get_output_files("gatk4_hc_joint", "run"),
    threads: wf.get_resource("gatk4_hc_joint", "run", "threads")
    resources:
        time=wf.get_resource("gatk4_hc_joint", "run", "time"),
        memory=wf.get_resource("gatk4_hc_joint", "run", "memory"),
        partition=wf.get_resource("gatk4_hc_joint", "run", "partition"),
        tmpdir=wf.get_resource("gatk4_hc_joint", "run", "tmpdir"),
    log:
        **wf.get_log_file("gatk4_hc_joint", "run"),
    wrapper:
        wf.wrapper_path("gatk4_hc/joint")


# Run GATK 4 HaplotypeCaller gVCF (going via per-sample gVCF files) -----------


# Discover variants with GATK HaplotypeCaller, create per-sample gVCF file
rule variant_calling_gatk4_hc_gvcf_discover:
    input:
        unpack(wf.get_input_files("gatk4_hc_gvcf", "discover")),
    output:
        **wf.get_output_files("gatk4_hc_gvcf", "discover"),
    threads: wf.get_resource("gatk4_hc_gvcf", "discover", "threads")
    resources:
        time=wf.get_resource("gatk4_hc_gvcf", "discover", "time"),
        memory=wf.get_resource("gatk4_hc_gvcf", "discover", "memory"),
        partition=wf.get_resource("gatk4_hc_gvcf", "discover", "partition"),
        tmpdir=wf.get_resource("gatk4_hc_gvcf", "discover", "tmpdir"),
    params:
        step_key="variant_calling",
        caller_key="gatk4_hc_gvcf",
    log:
        **wf.get_log_file("gatk4_hc_gvcf", "discover"),
    wrapper:
        wf.wrapper_path("gatk4_hc/discover")


# Combine the gVCF files from the pedigree with CombineGVCFs
rule variant_calling_gatk4_hc_gvcf_combine_gvcfs:
    input:
        unpack(wf.get_input_files("gatk4_hc_gvcf", "combine_gvcfs")),
    output:
        **wf.get_output_files("gatk4_hc_gvcf", "combine_gvcfs"),
    threads: wf.get_resource("gatk4_hc_gvcf", "combine_gvcfs", "threads")
    resources:
        time=wf.get_resource("gatk4_hc_gvcf", "combine_gvcfs", "time"),
        memory=wf.get_resource("gatk4_hc_gvcf", "combine_gvcfs", "memory"),
        partition=wf.get_resource("gatk4_hc_gvcf", "combine_gvcfs", "partition"),
        tmpdir=wf.get_resource("gatk4_hc_gvcf", "combine_gvcfs", "tmpdir"),
    params:
        step_key="variant_calling",
        caller_key="gatk4_hc_gvcf",
    log:
        **wf.get_log_file("gatk4_hc_gvcf", "combine_gvcfs"),
    wrapper:
        wf.wrapper_path("gatk4_hc/combine_gvcfs")


# Perform GenotypeGVCFs genotyping of all samples in each pedigree
rule variant_calling_gatk4_hc_gvcf_genotype:
    input:
        unpack(wf.get_input_files("gatk4_hc_gvcf", "genotype")),
    output:
        **wf.get_output_files("gatk4_hc_gvcf", "genotype"),
    threads: wf.get_resource("gatk4_hc_gvcf", "genotype", "threads")
    resources:
        time=wf.get_resource("gatk4_hc_gvcf", "genotype", "time"),
        memory=wf.get_resource("gatk4_hc_gvcf", "genotype", "memory"),
        partition=wf.get_resource("gatk4_hc_gvcf", "genotype", "partition"),
        tmpdir=wf.get_resource("gatk4_hc_gvcf", "genotype", "tmpdir"),
    params:
        step_key="variant_calling",
        caller_key="gatk4_hc_gvcf",
    log:
        **wf.get_log_file("gatk4_hc_gvcf", "genotype"),
    wrapper:
        wf.wrapper_path("gatk4_hc/genotype")


# QC / Statistics ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generate BCFtools stats report ----------------------------------------------


rule variant_calling_bcftools_stats_report:
    input:
        **wf.get_input_files("bcftools_stats", "run"),
    output:
        **wf.get_output_files("bcftools_stats", "run"),
    threads: wf.get_resource("bcftools_stats", "run", "threads")
    resources:
        time=wf.get_resource("bcftools_stats", "run", "time"),
        memory=wf.get_resource("bcftools_stats", "run", "memory"),
        partition=wf.get_resource("bcftools_stats", "run", "partition"),
        tmpdir=wf.get_resource("bcftools_stats", "run", "tmpdir"),
    log:
        **wf.get_log_file("bcftools_stats", "run"),
    wrapper:
        wf.wrapper_path("bcftools_stats/run")


# Generate Jannovar statistics report -----------------------------------------


rule variant_calling_jannovar_stats_report:
    input:
        **wf.get_input_files("jannovar_stats", "run"),
    output:
        **wf.get_output_files("jannovar_stats", "run"),
    threads: wf.get_resource("jannovar_stats", "run", "threads")
    resources:
        time=wf.get_resource("jannovar_stats", "run", "time"),
        memory=wf.get_resource("jannovar_stats", "run", "memory"),
        partition=wf.get_resource("jannovar_stats", "run", "partition"),
        tmpdir=wf.get_resource("jannovar_stats", "run", "tmpdir"),
    log:
        **wf.get_log_file("jannovar_stats", "run"),
    wrapper:
        wf.wrapper_path("jannovar/statistics")


# Generate B allele fraction files --------------------------------------------


rule variant_calling_baf_file_generation:
    input:
        **wf.get_input_files("baf_file_generation", "run"),
    output:
        **wf.get_output_files("baf_file_generation", "run"),
    threads: wf.get_resource("baf_file_generation", "run", "threads")
    resources:
        time=wf.get_resource("baf_file_generation", "run", "time"),
        memory=wf.get_resource("baf_file_generation", "run", "memory"),
        partition=wf.get_resource("baf_file_generation", "run", "partition"),
        tmpdir=wf.get_resource("baf_file_generation", "run", "tmpdir"),
    log:
        **wf.get_log_file("baf_file_generation", "run"),
    wrapper:
        wf.wrapper_path("baf_file_generation")


# Run bcftools roh ------------------------------------------------------------


rule variant_calling_bcftools_roh:
    input:
        **wf.get_input_files("bcftools_roh", "run"),
    output:
        **wf.get_output_files("bcftools_roh", "run"),
    threads: wf.get_resource("bcftools_roh", "run", "threads")
    resources:
        time=wf.get_resource("bcftools_roh", "run", "time"),
        memory=wf.get_resource("bcftools_roh", "run", "memory"),
        partition=wf.get_resource("bcftools_roh", "run", "partition"),
        tmpdir=wf.get_resource("bcftools_roh", "run", "tmpdir"),
    log:
        **wf.get_log_file("bcftools_roh", "run"),
    wrapper:
        wf.wrapper_path("bcftools_roh")
