channels:
  - conda-forge
  - bioconda
dependencies:
  - bwa ==0.7.17
  - samtools =1.16
  - samblaster ==0.1.26
  - seqtk ==1.3
  - trimadap ==r11
  - gnuplot ==5.4.5
  - libpng ==1.6.39
  - inline-html ==1.0.0
