# -*- coding: utf-8 -*-
"""CUBI Pipeline gene_expression_quantification step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Clemens Messerschmidt"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    gene_expression_quantification_link_in_run,
    gene_expression_quantification_link_out_run,


rule gene_expression_quantification_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Link in FASTQ files ---------------------------------------------------------


rule gene_expression_quantification_link_in_run:
    input:
        wf.get_input_files("link_in", "run"),
    output:
        wf.get_output_files("link_in", "run"),
    run:
        wf.run_locally("link_in", "run", wildcards)


# Generic linking out ---------------------------------------------------------


rule gene_expression_quantification_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Gene Expression Strandedness ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run RseQC infer_experiment.py ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule gene_expression_quantification_strandedness_run:
    input:
        unpack(wf.get_input_files("strandedness", "run")),
    output:
        **wf.get_output_files("strandedness", "run"),
    log:
        **wf.get_log_file("strandedness", "run"),
    threads: wf.get_resource("strandedness", "run", "threads")
    resources:
        runtime=wf.get_resource("strandedness", "run", "runtime"),
        mem=wf.get_resource("strandedness", "run", "mem"),
        partition=wf.get_resource("strandedness", "run", "partition"),
        tmpdir=wf.get_resource("strandedness", "run", "tmpdir"),
    params:
        args=wf.get_params("strandedness", "run"),
    wrapper:
        wf.wrapper_path("rseqc")


# Gene Expression QC ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule gene_expression_quantification_duplication_run:
    input:
        unpack(wf.get_input_files("duplication", "run")),
    output:
        **wf.get_output_files("duplication", "run"),
    log:
        **wf.get_log_file("duplication", "run"),
    threads: wf.get_resource("duplication", "run", "threads")
    resources:
        runtime=wf.get_resource("duplication", "run", "runtime"),
        mem=wf.get_resource("duplication", "run", "mem"),
        partition=wf.get_resource("duplication", "run", "partition"),
        tmpdir=wf.get_resource("duplication", "run", "tmpdir"),
    params:
        args=wf.get_params("duplication", "run"),
    wrapper:
        wf.wrapper_path("rnaqc/duplication")


rule gene_expression_quantification_dupradar_run:
    input:
        unpack(wf.get_input_files("dupradar", "run")),
    output:
        **wf.get_output_files("dupradar", "run"),
    log:
        **wf.get_log_file("dupradar", "run"),
    threads: wf.get_resource("dupradar", "run", "threads")
    resources:
        runtime=wf.get_resource("dupradar", "run", "runtime"),
        mem=wf.get_resource("dupradar", "run", "mem"),
        partition=wf.get_resource("dupradar", "run", "partition"),
        tmpdir=wf.get_resource("dupradar", "run", "tmpdir"),
    params:
        args=wf.get_params("dupradar", "run"),
    wrapper:
        wf.wrapper_path("rnaqc/dupradar")


rule gene_expression_quantification_rnaseqc_run:
    input:
        unpack(wf.get_input_files("rnaseqc", "run")),
    output:
        **wf.get_output_files("rnaseqc", "run"),
    log:
        **wf.get_log_file("rnaseqc", "run"),
    threads: wf.get_resource("rnaseqc", "run", "threads")
    resources:
        runtime=wf.get_resource("rnaseqc", "run", "runtime"),
        mem=wf.get_resource("rnaseqc", "run", "mem"),
        partition=wf.get_resource("rnaseqc", "run", "partition"),
        tmpdir=wf.get_resource("rnaseqc", "run", "tmpdir"),
    params:
        args=wf.get_params("rnaseqc", "run"),
    wrapper:
        wf.wrapper_path("rnaqc/rnaseqc")


rule gene_expression_quantification_stats_run:
    input:
        unpack(wf.get_input_files("stats", "run")),
    output:
        **wf.get_output_files("stats", "run"),
    log:
        **wf.get_log_file("stats", "run"),
    threads: wf.get_resource("stats", "run", "threads")
    resources:
        runtime=wf.get_resource("stats", "run", "runtime"),
        mem=wf.get_resource("stats", "run", "mem"),
        partition=wf.get_resource("stats", "run", "partition"),
        tmpdir=wf.get_resource("stats", "run", "tmpdir"),
    params:
        args=wf.get_params("stats", "run"),
    wrapper:
        wf.wrapper_path("rnaqc/stats")


# Gene Expression Quantification ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run FeatureCounts------------------------------------------------------------


rule gene_expression_quantification_featurecounts_run:
    input:
        unpack(wf.get_input_files("featurecounts", "run")),
    output:
        **wf.get_output_files("featurecounts", "run"),
    log:
        **wf.get_log_file("featurecounts", "run"),
    threads: wf.get_resource("featurecounts", "run", "threads")
    resources:
        runtime=wf.get_resource("featurecounts", "run", "runtime"),
        mem=wf.get_resource("featurecounts", "run", "mem"),
        partition=wf.get_resource("featurecounts", "run", "partition"),
        tmpdir=wf.get_resource("featurecounts", "run", "tmpdir"),
    params:
        args=wf.get_params("featurecounts", "run"),
    wrapper:
        wf.wrapper_path("featurecounts")


# Gene Expression Quantification ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run Salmon-------------------------------------------------------------------


rule gene_expression_quantification_salmon_run:
    input:
        unpack(wf.get_input_files("salmon", "run")),
    output:
        **wf.get_output_files("salmon", "run"),
    log:
        **wf.get_log_file("salmon", "run"),
    threads: wf.get_resource("salmon", "run", "threads")
    resources:
        runtime=wf.get_resource("salmon", "run", "runtime"),
        mem=wf.get_resource("salmon", "run", "mem"),
        partition=wf.get_resource("salmon", "run", "partition"),
        tmpdir=wf.get_resource("salmon", "run", "tmpdir"),
    params:
        args=wf.get_params("salmon", "run"),
    wrapper:
        wf.wrapper_path("salmon")
