# -*- coding: utf-8 -*-
"""CUBI Pipeline variant_filtration step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.variant_filtration import VariantFiltrationWorkflow

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = VariantFiltrationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally.
    variant_filtration_link_out_run,


# Special local rule for ebfilter write_panel (only active when tool=ebfilter)
if wf.config.tool == "ebfilter":

    localrules:
        variant_filtration_ebfilter_write_panel,

    rule variant_filtration_ebfilter_write_panel:
        output:
            **wf.get_output_files("filter", "write_panel"),
        threads: wf.get_resource("filter", "write_panel", "threads")
        resources:
            runtime=wf.get_resource("filter", "write_panel", "runtime"),
            mem=wf.get_resource("filter", "write_panel", "mem"),
            partition=wf.get_resource("filter", "write_panel", "partition"),
            tmpdir=wf.get_resource("filter", "write_panel", "tmpdir"),
        run:
            wf.substep_getattr("filter", "write_panel_of_normals_file")(wildcards)


rule variant_filtration_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule variant_filtration_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Variant Filtration ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if wf.config.tool == "bcftools":

    rule variant_filtration_filter_run:
        input:
            unpack(wf.get_input_files("filter", "run")),
        output:
            **wf.get_output_files("filter", "run"),
        log:
            **wf.get_log_file("filter", "run"),
        threads: wf.get_resource("filter", "run", "threads")
        resources:
            runtime=wf.get_resource("filter", "run", "runtime"),
            mem=wf.get_resource("filter", "run", "mem"),
            partition=wf.get_resource("filter", "run", "partition"),
            tmpdir=wf.get_resource("filter", "run", "tmpdir"),
        params:
            args=wf.get_args("filter", "run"),
        wrapper:
            wf.wrapper_path("bcftools/filter")

elif wf.config.tool == "vembrane":

    rule variant_filtration_filter_run:
        input:
            unpack(wf.get_input_files("filter", "run")),
        output:
            **wf.get_output_files("filter", "run"),
        log:
            **wf.get_log_file("filter", "run"),
        threads: wf.get_resource("filter", "run", "threads")
        resources:
            runtime=wf.get_resource("filter", "run", "runtime"),
            mem=wf.get_resource("filter", "run", "mem"),
            partition=wf.get_resource("filter", "run", "partition"),
            tmpdir=wf.get_resource("filter", "run", "tmpdir"),
        params:
            args=wf.get_args("filter", "run"),
        wrapper:
            wf.wrapper_path("vembrane/tag")

elif wf.config.tool == "regions":

    rule variant_filtration_filter_run:
        input:
            unpack(wf.get_input_files("filter", "run")),
        output:
            **wf.get_output_files("filter", "run"),
        log:
            **wf.get_log_file("filter", "run"),
        threads: wf.get_resource("filter", "run", "threads")
        resources:
            runtime=wf.get_resource("filter", "run", "runtime"),
            mem=wf.get_resource("filter", "run", "mem"),
            partition=wf.get_resource("filter", "run", "partition"),
            tmpdir=wf.get_resource("filter", "run", "tmpdir"),
        params:
            args=wf.get_args("filter", "run"),
        wrapper:
            wf.wrapper_path("bcftools/regions")

elif wf.config.tool == "dkfz":

    rule variant_filtration_filter_run:
        input:
            unpack(wf.get_input_files("filter", "run")),
        output:
            **wf.get_output_files("filter", "run"),
        log:
            **wf.get_log_file("filter", "run"),
        threads: wf.get_resource("filter", "run", "threads")
        resources:
            runtime=wf.get_resource("filter", "run", "runtime"),
            mem=wf.get_resource("filter", "run", "mem"),
            partition=wf.get_resource("filter", "run", "partition"),
            tmpdir=wf.get_resource("filter", "run", "tmpdir"),
        params:
            args=wf.get_args("filter", "run"),
        wrapper:
            wf.wrapper_path("dkfz_bias_filter")

elif wf.config.tool == "ebfilter":

    rule variant_filtration_filter_run:
        input:
            unpack(wf.get_input_files("filter", "run")),
        output:
            **wf.get_output_files("filter", "run"),
        log:
            **wf.get_log_file("filter", "run"),
        threads: wf.get_resource("filter", "run", "threads")
        resources:
            runtime=wf.get_resource("filter", "run", "runtime"),
            mem=wf.get_resource("filter", "run", "mem"),
            partition=wf.get_resource("filter", "run", "partition"),
            tmpdir=wf.get_resource("filter", "run", "tmpdir"),
        params:
            args=wf.get_args("filter", "run"),
        wrapper:
            wf.wrapper_path("eb_filter")
