# Variant Filtration ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Flexible Somatic Variant Filtration ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule one_dkfz:
    input:
        unpack(wf.get_input_files("one_dkfz", "run")),
    output:
        **wf.get_output_files("one_dkfz", "run"),
    params:
        args=wf.get_args("one_dkfz", "run"),
    threads: wf.get_resource("one_dkfz", "run", "threads")
    resources:
        time=wf.get_resource("one_dkfz", "run", "time"),
        memory=wf.get_resource("one_dkfz", "run", "memory"),
        partition=wf.get_resource("one_dkfz", "run", "partition"),
        tmpdir=wf.get_resource("one_dkfz", "run", "tmpdir"),
    log:
        **wf.get_log_file("one_dkfz", "run"),
    wrapper:
        wf.wrapper_path("dkfz_bias_filter")


rule one_bcftools:
    input:
        unpack(wf.get_input_files("one_bcftools", "run")),
    output:
        **wf.get_output_files("one_bcftools", "run"),
    params:
        args=wf.get_args("one_bcftools", "run"),
    threads: wf.get_resource("one_bcftools", "run", "threads")
    resources:
        time=wf.get_resource("one_bcftools", "run", "time"),
        memory=wf.get_resource("one_bcftools", "run", "memory"),
        partition=wf.get_resource("one_bcftools", "run", "partition"),
        tmpdir=wf.get_resource("one_bcftools", "run", "tmpdir"),
    log:
        **wf.get_log_file("one_bcftools", "run"),
    wrapper:
        wf.wrapper_path("bcftools/filter")


rule one_regions:
    input:
        unpack(wf.get_input_files("one_regions", "run")),
    output:
        **wf.get_output_files("one_regions", "run"),
    params:
        args=wf.get_args("one_regions", "run"),
    threads: wf.get_resource("one_regions", "run", "threads")
    resources:
        time=wf.get_resource("one_regions", "run", "time"),
        memory=wf.get_resource("one_regions", "run", "memory"),
        partition=wf.get_resource("one_regions", "run", "partition"),
        tmpdir=wf.get_resource("one_regions", "run", "tmpdir"),
    log:
        **wf.get_log_file("one_regions", "run"),
    wrapper:
        wf.wrapper_path("bcftools/regions")


rule one_protected:
    input:
        unpack(wf.get_input_files("one_protected", "run")),
    output:
        **wf.get_output_files("one_protected", "run"),
    params:
        args=wf.get_args("one_protected", "run"),
    threads: wf.get_resource("one_protected", "run", "threads")
    resources:
        time=wf.get_resource("one_protected", "run", "time"),
        memory=wf.get_resource("one_protected", "run", "memory"),
        partition=wf.get_resource("one_protected", "run", "partition"),
        tmpdir=wf.get_resource("one_protected", "run", "tmpdir"),
    log:
        **wf.get_log_file("one_protected", "run"),
    wrapper:
        wf.wrapper_path("bcftools/protected")


rule last_filter:
    input:
        **wf.get_input_files("last_filter", "run"),
    output:
        **wf.get_output_files("last_filter", "run"),
    threads: wf.get_resource("last_filter", "run", "threads")
    resources:
        time=wf.get_resource("last_filter", "run", "time"),
        memory=wf.get_resource("last_filter", "run", "memory"),
        partition=wf.get_resource("last_filter", "run", "partition"),
        tmpdir=wf.get_resource("last_filter", "run", "tmpdir"),
    log:
        **wf.get_log_file("last_filter", "run"),
    wrapper:
        wf.wrapper_path("somatic_variant_filtration/apply_all_filters")
