# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_variant_signatures step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Clemens Messerschmidt"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_variant_signatures_link_out_run,


rule somatic_variant_signatures_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_variant_signatures_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Somatic variant signatures ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Tabulate VCF ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule somatic_variant_signatures_tabulate_vcf:
    input:
        unpack(wf.get_input_files("tabulate_vcf", "run")),
    output:
        **wf.get_output_files("tabulate_vcf", "run"),
    log:
        wf.get_log_file("tabulate_vcf", "run"),
    benchmark:
        wf.get_benchmark_file("tabulate_vcf", "run")
    threads: wf.get_resource("tabulate_vcf", "run", "threads")
    resources:
        runtime=wf.get_resource("tabulate_vcf", "run", "runtime"),
        mem=wf.get_resource("tabulate_vcf", "run", "mem"),
        partition=wf.get_resource("tabulate_vcf", "run", "partition"),
        tmpdir=wf.get_resource("tabulate_vcf", "run", "tmpdir"),
    params:
        args=wf.get_params("tabulate_vcf", "run"),
    wrapper:
        wf.wrapper_path("signatures/tabulate_vcf")


# Run R deconstructSigs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule somatic_variant_signatures_deconstructsigs:
    input:
        unpack(wf.get_input_files("deconstruct_sigs", "run")),
    output:
        **wf.get_output_files("deconstruct_sigs", "run"),
    log:
        wf.get_log_file("deconstruct_sigs", "run"),
    benchmark:
        wf.get_benchmark_file("deconstruct_sigs", "run")
    threads: wf.get_resource("deconstruct_sigs", "run", "threads")
    resources:
        runtime=wf.get_resource("deconstruct_sigs", "run", "runtime"),
        mem=wf.get_resource("deconstruct_sigs", "run", "mem"),
        partition=wf.get_resource("deconstruct_sigs", "run", "partition"),
        tmpdir=wf.get_resource("deconstruct_sigs", "run", "tmpdir"),
    wrapper:
        wf.wrapper_path("signatures/deconstruct_sigs")
