# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_hla_loh_calling step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.somatic_hla_loh_calling import (
    SomaticHlaLohCallingWorkflow,
)

__author__ = "Clemens Messerschmidt"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = SomaticHlaLohCallingWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


# Modules =====================================================================


target_upstream = wf.depends_on.get("ngs_mapping", "ngs_mapping")
upstream_prefix = wf.config.get(f"path_ngs_mapping", f"../{target_upstream}")


module ngs_mapping:
    snakefile:
        "../ngs_mapping/Snakefile"
    config:
        wf.w_config
    prefix:
        upstream_prefix


use rule * from ngs_mapping as ngs_mapping_*


target_upstream = wf.depends_on.get("hla_typing", "hla_typing")
upstream_prefix = wf.config.get(f"path_hla_typing", f"../{target_upstream}")


module hla_typing:
    snakefile:
        "../hla_typing/Snakefile"
    config:
        wf.w_config
    prefix:
        upstream_prefix


use rule * from hla_typing as hla_typing_*


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_hla_loh_calling_link_out_run,


rule somatic_hla_loh_calling_all:
    input:
        wf.get_result_files(),
    default_target: True


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_hla_loh_calling_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Run LOHHLA ------------------------------------------------------------------


rule somatic_hla_loh_calling_lohhla:
    input:
        unpack(wf.get_input_files("lohhla", "run")),
    output:
        **wf.get_output_files("lohhla", "run"),
    threads: wf.get_resource("lohhla", "run", "threads")
    resources:
        runtime=wf.get_resource("lohhla", "run", "runtime"),
        mem=wf.get_resource("lohhla", "run", "mem"),
        partition=wf.get_resource("lohhla", "run", "partition"),
        tmpdir=wf.get_resource("lohhla", "run", "tmpdir"),
    log:
        **wf.get_log_file("lohhla", "run"),
    wrapper:
        wf.wrapper_path("lohhla")
