# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_hla_loh_calling step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Clemens Messerschmidt"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_hla_loh_calling_link_out_run,


rule somatic_hla_loh_calling_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_hla_loh_calling_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Run LOHHLA ------------------------------------------------------------------


rule somatic_hla_loh_calling_lohhla:
    input:
        unpack(wf.get_input_files("lohhla", "run")),
    output:
        **wf.get_output_files("lohhla", "run"),
    log:
        **wf.get_log_file("lohhla", "run"),
    benchmark:
        wf.get_benchmark_file("lohhla", "run")
    threads: wf.get_resource("lohhla", "run", "threads")
    resources:
        runtime=wf.get_resource("lohhla", "run", "runtime"),
        mem=wf.get_resource("lohhla", "run", "mem"),
        partition=wf.get_resource("lohhla", "run", "partition"),
        tmpdir=wf.get_resource("lohhla", "run", "tmpdir"),
    wrapper:
        wf.wrapper_path("lohhla")
