# -*- coding: utf-8 -*-
"""CUBI Pipeline wgs_cnv_export_external step Snakefile"""

from snappy_pipeline.orchestration import task_instance

# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])

# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    wgs_cnv_export_external_link_out_run,
    # Writing pedigrees should be done locally as well
    wgs_cnv_export_external_write_pedigree_run,


rule wgs_cnv_export_external_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule wgs_cnv_export_external_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Annotation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Write out pedigree file -----------------------------------------------------


rule wgs_cnv_export_external_write_pedigree_run:
    output:
        wf.get_output_files("write_pedigree_with_sample_name", "run"),
    run:
        wf.substep_dispatch("write_pedigree_with_sample_name", "run", wildcards, output)


# Merge external VCFs by pedigree (if necessary) ------------------------------


rule wgs_cnv_export_external_varfish_annotator_external_merge_vcf:
    input:
        unpack(wf.get_input_files("varfish_annotator_external", "merge_vcf")),
    output:
        **wf.get_output_files("varfish_annotator_external", "merge_vcf"),
    log:
        **wf.get_log_file("varfish_annotator_external", "merge_vcf"),
    threads: wf.get_resource("varfish_annotator_external", "merge_vcf", "threads")
    resources:
        runtime=wf.get_resource("varfish_annotator_external", "merge_vcf", "runtime"),
        mem=wf.get_resource("varfish_annotator_external", "merge_vcf", "mem"),
        partition=wf.get_resource("varfish_annotator_external", "merge_vcf", "partition"),
        tmpdir=wf.get_resource("varfish_annotator_external", "merge_vcf", "tmpdir"),
    params:
        args=wf.get_params("varfish_annotator_external", "merge_vcf"),
    wrapper:
        wf.wrapper_path("bcftools/merge_vcf")


# Run varfish-annotator-cli annotate ------------------------------------------


rule wgs_cnv_export_external_varfish_annotator_external_annotate_svs:
    input:
        unpack(wf.get_input_files("varfish_annotator_external", "annotate")),
    output:
        **wf.get_output_files("varfish_annotator_external", "annotate"),
    log:
        **wf.get_log_file("varfish_annotator_external", "annotate"),
    threads: wf.get_resource("varfish_annotator_external", "annotate", "threads")
    resources:
        runtime=wf.get_resource("varfish_annotator_external", "annotate", "runtime"),
        mem=wf.get_resource("varfish_annotator_external", "annotate", "mem"),
        partition=wf.get_resource("varfish_annotator_external", "annotate", "partition"),
        tmpdir=wf.get_resource("varfish_annotator_external", "annotate", "tmpdir"),
    params:
        args=wf.get_params("varfish_annotator_external", "annotate"),
    wrapper:
        wf.wrapper_path("varfish_annotator/annotate_svs")
