# -*- coding: utf-8 -*-
"""CUBI Pipeline tumor mutational burden step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.somatic_variant_qc import (
    SomaticVariantQCWorkflow,
)

__author__ = "Gia Cuong Pham"
__email__ = "pham.gia-cuong@bih-charite.de"


# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================
wf = SomaticVariantQCWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_variant_qc_link_out_run,


rule all:
    input:
        wf.get_result_files(),


# Generic linking out ---------------------------------------------------------


rule somatic_variant_qc_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        shell(wf.get_shell_cmd("link_out", "run", wildcards))


rule somatic_variant_qc:
    input:
        **wf.get_input_files("SVQC_step", "run"),
    output:
        **wf.get_output_files("SVQC_step", "run"),
    threads: wf.get_resource("SVQC_step", "run", "threads")
    resources:
        time=wf.get_resource("SVQC_step", "run", "time"),
        memory=wf.get_resource("SVQC_step", "run", "memory"),
        partition=wf.get_resource("SVQC_step", "run", "partition"),
        tmpdir=wf.get_resource("SVQC_step", "run", "tmpdir"),
    log:
        **wf.get_log_file("SVQC_step", "run"),
    wrapper:
        wf.wrapper_path("somatic_variants_qc")
