# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_purity_ploidy_estimate step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_purity_ploidy_estimate_link_out_run,


rule somatic_purity_ploidy_estimate_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_purity_ploidy_estimate_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Somatic Purity and Ploidy Estimation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Decide if WGS or WES rules should be used:

if wf.depends_on.get("somatic_targeted_seq_cnv_calling"):

    ruleorder: somatic_purity_ploidy_estimate_ascat_cnv_tumor > somatic_purity_ploidy_estimate_ascat_cnv_tumor_wes
    ruleorder:
        somatic_purity_ploidy_estimate_ascat_cnv_normal
        > somatic_purity_ploidy_estimate_ascat_cnv_normal_wes

else:

    ruleorder: somatic_purity_ploidy_estimate_ascat_cnv_tumor_wes > somatic_purity_ploidy_estimate_ascat_cnv_tumor
    ruleorder:
        somatic_purity_ploidy_estimate_ascat_cnv_normal_wes
        > somatic_purity_ploidy_estimate_ascat_cnv_normal


# ASCAT and Supporting Steps --------------------------------------------------
# Get B-allele frequencies from bam - steps are the same for WES and WGS ------
rule somatic_purity_ploidy_estimate_ascat_baf_tumor:
    input:
        unpack(wf.get_input_files("ascat", "baf_tumor")),
    output:
        **wf.get_output_files("ascat", "baf_tumor"),
    log:
        **wf.get_log_file("ascat", "baf_tumor"),
    benchmark:
        wf.get_benchmark_file("ascat", "baf_tumor")
    threads: wf.get_resource("ascat", "baf_tumor", "threads")
    resources:
        runtime=wf.get_resource("ascat", "baf_tumor", "runtime"),
        mem=wf.get_resource("ascat", "baf_tumor", "mem"),
        partition=wf.get_resource("ascat", "baf_tumor", "partition"),
        tmpdir=wf.get_resource("ascat", "baf_tumor", "tmpdir"),
    wrapper:
        wf.wrapper_path("ascat/build_baf")


rule somatic_purity_ploidy_estimate_ascat_baf_normal:
    input:
        unpack(wf.get_input_files("ascat", "baf_normal")),
    output:
        **wf.get_output_files("ascat", "baf_normal"),
    log:
        **wf.get_log_file("ascat", "baf_normal"),
    benchmark:
        wf.get_benchmark_file("ascat", "baf_normal")
    threads: wf.get_resource("ascat", "baf_normal", "threads")
    resources:
        runtime=wf.get_resource("ascat", "baf_normal", "runtime"),
        mem=wf.get_resource("ascat", "baf_normal", "mem"),
        partition=wf.get_resource("ascat", "baf_normal", "partition"),
        tmpdir=wf.get_resource("ascat", "baf_normal", "tmpdir"),
    wrapper:
        wf.wrapper_path("ascat/build_baf")


# Get logR for tumor and normal in WGS ----------------------------------------


rule somatic_purity_ploidy_estimate_ascat_cnv_tumor:
    input:
        unpack(wf.get_input_files("ascat", "cnv_tumor")),
    output:
        **wf.get_output_files("ascat", "cnv_tumor"),
    log:
        **wf.get_log_file("ascat", "cnv_tumor"),
    benchmark:
        wf.get_benchmark_file("ascat", "cnv_tumor")
    threads: wf.get_resource("ascat", "cnv_tumor", "threads")
    resources:
        runtime=wf.get_resource("ascat", "cnv_tumor", "runtime"),
        mem=wf.get_resource("ascat", "cnv_tumor", "mem"),
        partition=wf.get_resource("ascat", "cnv_tumor", "partition"),
        tmpdir=wf.get_resource("ascat", "cnv_tumor", "tmpdir"),
    params:
        args=wf.get_params("ascat", "cnv_tumor"),
    wrapper:
        wf.wrapper_path("ascat/build_cnv")


rule somatic_purity_ploidy_estimate_ascat_cnv_normal:
    input:
        unpack(wf.get_input_files("ascat", "cnv_normal")),
    output:
        **wf.get_output_files("ascat", "cnv_normal"),
    log:
        **wf.get_log_file("ascat", "cnv_normal"),
    benchmark:
        wf.get_benchmark_file("ascat", "cnv_normal")
    threads: wf.get_resource("ascat", "cnv_normal", "threads")
    resources:
        runtime=wf.get_resource("ascat", "cnv_normal", "runtime"),
        mem=wf.get_resource("ascat", "cnv_normal", "mem"),
        partition=wf.get_resource("ascat", "cnv_normal", "partition"),
        tmpdir=wf.get_resource("ascat", "cnv_normal", "tmpdir"),
    wrapper:
        wf.wrapper_path("ascat/build_cnv")


# get logR for tumor and normal from WES --------------------------------------


rule somatic_purity_ploidy_estimate_ascat_cnv_tumor_wes:
    input:
        unpack(wf.get_input_files("ascat", "cnv_tumor_wes")),
    output:
        **wf.get_output_files("ascat", "cnv_tumor"),
    log:
        **wf.get_log_file("ascat", "cnv_tumor"),
    benchmark:
        wf.get_benchmark_file("ascat", "cnv_tumor")
    threads: wf.get_resource("ascat", "cnv_tumor", "threads")
    resources:
        runtime=wf.get_resource("ascat", "cnv_tumor", "runtime"),
        mem=wf.get_resource("ascat", "cnv_tumor", "mem"),
        partition=wf.get_resource("ascat", "cnv_tumor", "partition"),
        tmpdir=wf.get_resource("ascat", "cnv_tumor", "tmpdir"),
    params:
        args=wf.get_params("ascat", "cnv_tumor"),
    wrapper:
        wf.wrapper_path("ascat/build_cnv_from_copywriter")


rule somatic_purity_ploidy_estimate_ascat_cnv_normal_wes:
    input:
        unpack(wf.get_input_files("ascat", "cnv_normal_wes")),
    output:
        **wf.get_output_files("ascat", "cnv_normal"),
    log:
        **wf.get_log_file("ascat", "cnv_normal"),
    benchmark:
        wf.get_benchmark_file("ascat", "cnv_normal")
    threads: wf.get_resource("ascat", "cnv_normal", "threads")
    resources:
        runtime=wf.get_resource("ascat", "cnv_normal", "runtime"),
        mem=wf.get_resource("ascat", "cnv_normal", "mem"),
        partition=wf.get_resource("ascat", "cnv_normal", "partition"),
        tmpdir=wf.get_resource("ascat", "cnv_normal", "tmpdir"),
    wrapper:
        wf.wrapper_path("ascat/build_cnv_from_copywriter")


# run ASCAT R package with prepared input files -------------------------------


rule somatic_purity_ploidy_estimate_ascat_run_ascat:
    input:
        unpack(wf.get_input_files("ascat", "run_ascat")),
    output:
        **wf.get_output_files("ascat", "run_ascat"),
    log:
        **wf.get_log_file("ascat", "run_ascat"),
    benchmark:
        wf.get_benchmark_file("ascat", "run_ascat")
    threads: wf.get_resource("ascat", "run_ascat", "threads")
    resources:
        runtime=wf.get_resource("ascat", "run_ascat", "runtime"),
        mem=wf.get_resource("ascat", "run_ascat", "mem"),
        partition=wf.get_resource("ascat", "run_ascat", "partition"),
        tmpdir=wf.get_resource("ascat", "run_ascat", "tmpdir"),
    params:
        args=wf.get_params("ascat", "run_ascat"),
    wrapper:
        wf.wrapper_path("ascat/run_ascat")
