# Variant Annotation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run VEP ---------------------------------------------------------------------

if "vep" in tools:

    if wf.config["vep"]["plugins"]:

        rule any_variant_annotation_vep_plugins:
            output:
                wf.get_output_files("vep", "plugins"),
            params:
                args=wf.get_args("vep", "plugins"),
            wrapper:
                wf.wrapper_path("vep/plugins")

    rule any_variant_annotation_vep_run:
        input:
            **wf.get_input_files("vep", "run"),
        output:
            **wf.get_output_files("vep", "run"),
        threads: wf.get_resource("vep", "run", "threads")
        resources:
            time=wf.get_resource("vep", "run", "time"),
            memory=wf.get_resource("vep", "run", "memory"),
            partition=wf.get_resource("vep", "run", "partition"),
            tmpdir=wf.get_resource("vep", "run", "tmpdir"),
        params:
            args=wf.get_args("vep", "run"),
        log:
            **wf.get_log_file("vep", "run"),
        wrapper:
            wf.wrapper_path("vep/run")
