# -*- coding: utf-8 -*-
"""CUBI Pipeline homologous_recombination_deficiency step Snakefile"""

from snappy_pipeline.orchestration import task_instance

__author__ = "Eric Blanc"


# WorkflowImpl Object Setup ===================================================

wf = task_instance(config["__task_name__"])


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    homologous_recombination_deficiency_link_out_run,


rule homologous_recombination_deficiency_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule homologous_recombination_deficiency_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Homologous Recombination Deficiency score ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run scarHRD -----------------------------------------------------------------


rule homologous_recombination_deficiency_scarHRD_install:
    output:
        **wf.get_output_files("scarHRD", "install"),
    log:
        **wf.get_log_file("scarHRD", "install"),
    resources:
        runtime=wf.get_resource("scarHRD", "install", "runtime"),
        mem=wf.get_resource("scarHRD", "install", "mem"),
        partition=wf.get_resource("scarHRD", "install", "partition"),
        tmpdir=wf.get_resource("scarHRD", "install", "tmpdir"),
    params:
        packages=[
            {"name": "aroneklund/copynumber", "repo": "github"},
            {"name": "sequenzatools/sequenza@3.0.0", "repo": "bitbucket"},
            {"name": "sztup/scarHRD", "repo": "github"},
        ],
    wrapper:
        wf.wrapper_path("scarHRD/install")


rule homologous_recombination_deficiency_scarHRD_run:
    input:
        unpack(wf.get_input_files("scarHRD", "run")),
    output:
        **wf.get_output_files("scarHRD", "run"),
    log:
        **wf.get_log_file("scarHRD", "run"),
    threads: wf.get_resource("scarHRD", "run", "threads")
    resources:
        runtime=wf.get_resource("scarHRD", "run", "runtime"),
        mem=wf.get_resource("scarHRD", "run", "mem"),
        partition=wf.get_resource("scarHRD", "run", "partition"),
        tmpdir=wf.get_resource("scarHRD", "run", "tmpdir"),
    params:
        args=wf.get_params("scarHRD", "run"),
    wrapper:
        wf.wrapper_path("scarHRD/run")
