# -*- coding: utf-8 -*-
"""CUBI Pipeline somatic_variant_annotation step Snakefile"""

import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.somatic_variant_annotation import (
    SomaticVariantAnnotationWorkflow,
)

__author__ = "Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"

# Configuration ===============================================================


configfile: "config.yaml"


# Expand "$ref" JSON pointers in configuration (also works for YAML)
config, lookup_paths, config_paths = expand_ref("config.yaml", config)

# WorkflowImpl Object Setup ===================================================

wf = SomaticVariantAnnotationWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


# Rules =======================================================================


localrules:
    # Linking files from work/ to output/ should be done locally
    somatic_variant_annotation_link_out_run,


rule somatic_variant_annotation_all:
    default_target: True
    input:
        wf.get_result_files(),


# House-Keeping ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Generic linking out ---------------------------------------------------------


rule somatic_variant_annotation_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


# Somatic Variant Annotation ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Run VEP ---------------------------------------------------------------------


rule somatic_variant_annotation_vep:
    input:
        **wf.get_input_files("vep", "run"),
    output:
        **wf.get_output_files("vep", "run"),
    log:
        **wf.get_log_file("vep", "run"),
    threads: wf.get_resource("vep", "run", "threads")
    resources:
        runtime=wf.get_resource("vep", "run", "runtime"),
        mem=wf.get_resource("vep", "run", "mem"),
        partition=wf.get_resource("vep", "run", "partition"),
        tmpdir=wf.get_resource("vep", "run", "tmpdir"),
    params:
        args=wf.get_args("vep", "run"),
    wrapper:
        wf.wrapper_path("vep/run")


# Run mehari ------------------------------------------------------------------


rule somatic_variant_annotation_mehari:
    input:
        **wf.get_input_files("mehari", "run"),
    output:
        **wf.get_output_files("mehari", "run"),
    log:
        **wf.get_log_file("mehari", "run"),
    threads: wf.get_resource("mehari", "run", "threads")
    resources:
        runtime=wf.get_resource("mehari", "run", "runtime"),
        mem=wf.get_resource("mehari", "run", "mem"),
        partition=wf.get_resource("mehari", "run", "partition"),
        tmpdir=wf.get_resource("mehari", "run", "tmpdir"),
    params:
        args=wf.get_args("mehari", "run"),
    wrapper:
        wf.wrapper_path("mehari/run")
