channels:
- conda-forge
- bioconda
- anaconda
dependencies:
- r-base=4.1
- r-matrixstats
- r-magrittr
- bioconductor-copywriter
- bioconductor-dnacopy
- bioconductor-cghcall
- bioconductor-rsamtools
- bioconductor-org.hs.eg.db
- bioconductor-ensdb.hsapiens.v75
- bioconductor-ensdb.hsapiens.v86
- bioconductor-txdb.hsapiens.ucsc.hg19.knownGene
- bioconductor-txdb.hsapiens.ucsc.hg38.knownGene
- bcftools
- samtools
- htslib
- openblas
