import os

from snappy_pipeline import expand_ref
from snappy_pipeline.workflows.create_proteome import CreateProteomeWorkflow


configfile: "config.yaml"


config, lookup_paths, config_paths = expand_ref("config.yaml", config)

wf = CreateProteomeWorkflow(workflow, config, lookup_paths, config_paths, os.getcwd())


localrules:
    create_proteome_link_out_run,


rule create_proteome_all:
    default_target: True
    input:
        wf.get_result_files(),


rule create_proteome_link_out_run:
    input:
        wf.get_input_files("link_out", "run"),
    output:
        wf.get_output_files("link_out", "run"),
    run:
        wf.run_locally("link_out", "run", wildcards)


rule create_proteome_run:
    input:
        unpack(wf.get_input_files("create_proteome", "run")),
    output:
        **wf.get_output_files("create_proteome", "run"),
    log:
        **wf.get_log_file("create_proteome", "run"),
    threads: wf.get_resource("create_proteome", "run", "threads")
    resources:
        runtime=wf.get_resource("create_proteome", "run", "runtime"),
        mem=wf.get_resource("create_proteome", "run", "mem"),
        partition=wf.get_resource("create_proteome", "run", "partition"),
        tmpdir=wf.get_resource("create_proteome", "run", "tmpdir"),
    params:
        args=wf.get_args("create_proteome", "run"),
    wrapper:
        wf.wrapper_path("pvactools/create_proteome")
