name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches_ignore: []


jobs:

  Dryrun_Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Test workflow (local FASTQs)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .tests/test-workflow
        snakefile: .tests/test-workflow/workflow/Snakefile
        args: "--configfile .tests/test-workflow/config/config.yaml --use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --dryrun"
        show-disk-usage-on-error: true


  Tests:
    runs-on: ubuntu-latest
    needs:
      - Dryrun_Tests
    steps:
    - name: update apt
      run: sudo apt-get update
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Test workflow (local FASTQs)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .tests/test-workflow
        snakefile: .tests/test-workflow/workflow/Snakefile
        args: "--configfile .tests/test-workflow/config/config.yaml --use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache"
        show-disk-usage-on-error: true

