name: Tests

on:
  # always run tests when pushing to main
  push:
    branches: [ main ]

  # only run tests on pull requests which actually modify files that affect the tests
  pull_request:
    branches_ignore: []
    # for now, the tests defined in this file are only run when any of the following paths are modified:
    paths:
      # workflow definitions
      - '.tests/**'

      # github workflow configurations
      - '.github/**'

      # 'base' files of snappy-pipeline
      - 'snappy_pipeline/*'
      - 'snappy_pipeline/workflows/abstract/**'

      # steps used in the test workflows
      - 'snappy_pipeline/workflows/ngs_mapping/**'
      - 'snappy_pipeline/workflows/somatic_variant_calling/**'
      - 'snappy_pipeline/workflows/somatic_variant_annotation/**'
      - 'snappy_pipeline/workflows/somatic_variant_filtration/**'

      # 'base' files of snappy_wrappers
      - 'snappy_wrappers/*'

      # wrappers used in the test workflows
      - 'snappy_wrappers/wrappers/alfred/**'
      - 'snappy_wrappers/wrappers/bcftools/**'
      - 'snappy_wrappers/wrappers/bwa/**'
      - 'snappy_wrappers/wrappers/link_in_bam/**'
      - 'snappy_wrappers/wrappers/mutect/**'
      - 'snappy_wrappers/wrappers/mutect_par/**'
      - 'snappy_wrappers/wrappers/mutect2/**'
      - 'snappy_wrappers/wrappers/mutect2_par/**'
      - 'snappy_wrappers/wrappers/ngs_chew/**'
      - 'snappy_wrappers/wrappers/somatic_variant_filtration/**'
      - 'snappy_wrappers/wrappers/vep/**'

defaults:
  run:
    shell: bash -el {0}

jobs:

  Dryrun_Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Setup conda
      uses: ./.github/actions/conda-cache
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml

    - name: Test workflow (local FASTQs)
      uses: snakemake/snakemake-github-action@cebcb23c87aa3a23efddff3f79b3a4bd143d4120
      with:
        directory: .tests/test-workflow
        snakefile: .tests/test-workflow/workflow/Snakefile
        args: "--configfile .tests/test-workflow/config/config.yaml --use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --dryrun"
        show-disk-usage-on-error: true
        snakemake-version: 7.32.4


  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    needs:
      - Dryrun_Tests
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Setup conda
      uses: ./.github/actions/conda-cache
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml

    - name: Test workflow (local FASTQs)
      uses: snakemake/snakemake-github-action@cebcb23c87aa3a23efddff3f79b3a4bd143d4120
      with:
        directory: .tests/test-workflow
        snakefile: .tests/test-workflow/workflow/Snakefile
        args: "--configfile .tests/test-workflow/config/config.yaml --use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache"
        show-disk-usage-on-error: true
        snakemake-version: 8.25.5

