name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: [ ]

defaults:
  run:
    shell: bash

env:
  PIXI_VERSION: v0.75.0

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          environments: dev
          cache: true
          frozen: true

      - name: Run linting tools
        run: pixi run -e dev lint

      - name: Comment PR
        if: github.event_name == 'pull_request' && failure()
        uses: marocchino/sticky-pull-request-comment@v1.1.0
        with:
          message: |
            - Please format your Python code with [ruff](https://docs.astral.sh/ruff/): `pixi run -e dev fmt`
            - Please check your Python code with [ruff](https://docs.astral.sh/ruff/): `pixi run -e dev check`
            - Please format your Snakemake code with [snakefmt](https://github.com/snakemake/snakefmt): `pixi run -e dev snakefmt`

            You can trigger all lints locally by running `pixi run -e dev lint`
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  testing:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 2

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          environments: test
          cache: true
          frozen: true

      - name: Run tests
        run: pixi run -e test test
        env:
          DIFF_MAIN: ${{ github.event_name == 'pull_request' }}
          DIFF_LAST_COMMIT: ${{ github.ref == 'refs/heads/main' }}

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          environments: docs
          cache: true
          frozen: true

      - name: Build documentation
        run: pixi run -e docs docs
